#!/usr/bin/env python3
"""Build internal/frontend/www/js/i18n.generated.js from the message catalogues.

The UI is a Vue 2 app whose strings are resolved through VueI18n. The
catalogues are kept as flat `namespace.name` JSON so that a review diff shows
one line per string; this script nests them, because `$t('peer.add')` resolves
against nested objects in VueI18n.

Run from the repository root:

    python3 internal/frontend/i18n/merge.py

Adding a language
-----------------
1. Drop `messages.<code>.json` next to this file (same keys as messages.en.json).
2. Add `<code>` to the language selector in
   `internal/frontend/templates/views/settings.html`.
3. Re-run this script.
"""
from __future__ import annotations

import json
import sys
from collections import OrderedDict
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT_FILE = HERE.parent / "www" / "js" / "i18n.generated.js"
SOURCE_LOCALE = "en"


def load(locale: str) -> dict:
    path = HERE / f"messages.{locale}.json"
    if not path.is_file():
        sys.exit(f"missing catalogue: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        sys.exit(f"{path}: top level must be an object")
    return data


def available_locales() -> list:
    return sorted(p.name[len("messages."):-len(".json")] for p in HERE.glob("messages.*.json"))


def nest(flat: dict) -> OrderedDict:
    tree: dict = {}
    for key in sorted(flat, key=lambda k: k.split(".", 1)):
        if "." not in key:
            sys.exit(f"key {key!r} must be namespaced (e.g. 'peer.add')")
        ns, name = key.split(".", 1)
        tree.setdefault(ns, OrderedDict())[name] = flat[key]
    return OrderedDict(sorted(tree.items()))


def main() -> int:
    locales = available_locales()
    if SOURCE_LOCALE not in locales:
        sys.exit(f"source catalogue messages.{SOURCE_LOCALE}.json is required")

    reference = load(SOURCE_LOCALE)
    catalogues = {}
    problems = []

    for locale in locales:
        flat = load(locale)
        missing = sorted(set(reference) - set(flat))
        extra = sorted(set(flat) - set(reference))
        empty = sorted(k for k, v in flat.items() if not isinstance(v, str) or not v.strip())
        for key in missing:
            problems.append(f"messages.{locale}.json: missing key {key!r} (present in {SOURCE_LOCALE})")
        for key in extra:
            problems.append(f"messages.{locale}.json: key {key!r} is not in {SOURCE_LOCALE}")
        for key in empty:
            problems.append(f"messages.{locale}.json: {key!r} is not a non-empty string")
        catalogues[locale] = nest(flat)

    if problems:
        print("VALIDATION ERRORS:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    lines = [
        "'use strict';",
        "",
        "// AUTO-GENERATED by internal/frontend/i18n/merge.py — DO NOT EDIT BY HAND.",
        "// Source of truth: internal/frontend/i18n/messages.<locale>.json",
        "// Merged into the message catalogue by i18n.js.",
        "/* eslint-disable */",
        "",
        "export const extraMessages = {",
    ]
    for locale in locales:
        body = json.dumps(catalogues[locale], ensure_ascii=False, indent=2)
        lines.append(f"  {locale}: " + body.replace("\n", "\n  ") + ",")
    lines.append("};")

    OUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

    sizes = ", ".join(f"{loc}={len(load(loc))}" for loc in locales)
    print(f"wrote {OUT_FILE.relative_to(HERE.parent.parent.parent)} ({sizes})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
