package tunnel

import (
	"fmt"
	"strings"
	"testing"
)

// TestRestartWithNewSettingsSteps_MSS verifies that each restart removes the
// rules generated by the old configuration before adding the new rules.
func TestRestartWithNewSettingsSteps_MSS(t *testing.T) {
	active := map[string]bool{}
	oldMSS := "--clamp-mss-to-pmtu"
	newMSS := oldMSS
	var order []string

	restart := func() error {
		return restartWithNewSettingsSteps(
			func() error {
				order = append(order, "stop")
				delete(active, oldMSS)
				return nil
			},
			func() error {
				order = append(order, "save")
				oldMSS = newMSS
				return nil
			},
			func() error {
				order = append(order, "regenerate")
				return nil
			},
			func() error {
				order = append(order, "start")
				active[newMSS] = true
				return nil
			},
		)
	}

	for _, mss := range []string{"--set-mss 1260", "--set-mss 1280"} {
		newMSS = mss
		if err := restart(); err != nil {
			t.Fatalf("restart MSS %s: %v", mss, err)
		}
		if len(active) != 1 || !active[mss] {
			t.Fatalf("active MSS rules = %#v, want only %q", active, mss)
		}
	}

	wantOrder := []string{"stop", "save", "regenerate", "start", "stop", "save", "regenerate", "start"}
	if strings.Join(order, ",") != strings.Join(wantOrder, ",") {
		t.Fatalf("lifecycle order = %v, want %v", order, wantOrder)
	}
}

// TestRestartWithNewSettingsSteps_NATDisable verifies that disabling NAT
// removes the previously generated MASQUERADE rule during the old-config stop.
func TestRestartWithNewSettingsSteps_NATDisable(t *testing.T) {
	active := map[string]bool{"masquerade": true}
	natEnabled := false
	var order []string

	err := restartWithNewSettingsSteps(
		func() error {
			order = append(order, "stop")
			delete(active, "masquerade")
			return nil
		},
		func() error {
			order = append(order, "save")
			natEnabled = false
			return nil
		},
		func() error {
			order = append(order, "regenerate")
			return nil
		},
		func() error {
			order = append(order, "start")
			if natEnabled {
				active["masquerade"] = true
			}
			return nil
		},
	)
	if err != nil {
		t.Fatalf("restart with NAT disabled: %v", err)
	}
	if active["masquerade"] {
		t.Fatal("stale MASQUERADE rule remained after NAT was disabled")
	}

	if got := fmt.Sprint(order); got != "[stop save regenerate start]" {
		t.Fatalf("lifecycle order = %s", got)
	}
}

func TestGenerateWgConfig_MSSAndNATSettings(t *testing.T) {
	iface := newTestIface()
	iface.MSS = -1
	cfg := iface.generateWgConfig()
	if !strings.Contains(cfg, "--clamp-mss-to-pmtu") {
		t.Fatal("Auto MSS configuration is missing its clamp rule")
	}
	if strings.Contains(cfg, "--set-mss") {
		t.Fatal("Auto MSS configuration contains a manual MSS rule")
	}

	iface.MSS = 1260
	cfg = iface.generateWgConfig()
	if !strings.Contains(cfg, "--set-mss 1260") || strings.Contains(cfg, "--set-mss 1280") {
		t.Fatal("MSS 1260 configuration contains an incorrect MSS rule")
	}
	iface.MSS = 1280
	cfg = iface.generateWgConfig()
	if !strings.Contains(cfg, "--set-mss 1280") || strings.Contains(cfg, "--set-mss 1260") {
		t.Fatal("MSS 1280 configuration contains an incorrect MSS rule")
	}

	iface.NatDisabled = false
	if !strings.Contains(iface.generateWgConfig(), "MASQUERADE") {
		t.Fatal("NAT-enabled configuration is missing MASQUERADE")
	}
	iface.NatDisabled = true
	if strings.Contains(iface.generateWgConfig(), "MASQUERADE") {
		t.Fatal("NAT-disabled configuration still contains MASQUERADE")
	}
}
