// Package tunnel manages WireGuard/AmneziaWG tunnel interfaces.
//
// Each TunnelInterface wraps one kernel interface (wg10, wg11, …) and owns:
//   - SQLite persistence (interfaces table)
//   - wg-quick / awg-quick lifecycle (start / stop / reload)
//   - in-memory peer cache (populated from SQLite, updated on mutations)
//   - runtime status polling (`wg/awg show dump`)
//
// Critical fixes ported from Node.js (CLAUDE.md):
//
//	FIX-1  iptables-nft + -A FORWARD (not -I), both -i and -o directions
//	FIX-2  RegenerateConfig before Start(); down→up on "already exists"
//	FIX-3  Stop() ignores "not a WireGuard/AmneziaWG interface"
//	FIX-7  quickBin/syncBin chosen by protocol
//	FIX-8  KernelRemovePeer → Restart for AWG2 (mutex, fire-and-forget goroutine)
//	FIX-9  KernelSetPeer   → Reload for AWG2, wg set peer for WG1 (mutex)
//	FIX-10 GetStatus uses ExecSilentFast (5 s timeout, no log — runs every second)
package tunnel

import (
	"database/sql"
	"encoding/binary"
	"fmt"
	"log"
	"net"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/alexnikon/cascade/internal/aliases"
	"github.com/alexnikon/cascade/internal/awgparams"
	"github.com/alexnikon/cascade/internal/db"
	"github.com/alexnikon/cascade/internal/metrics"
	"github.com/alexnikon/cascade/internal/peer"
	"github.com/alexnikon/cascade/internal/tc"
	"github.com/alexnikon/cascade/internal/util"
	"github.com/alexnikon/cascade/internal/validate"
)

// peerTrafficState tracks per-peer traffic accumulation in memory.
// lastSeenRx/Tx: kernel counter value at the previous poll tick (for delta).
// totalRx/Tx:   lifetime accumulated bytes (loaded from DB on startup, flushed periodically).
// dirty:        true when totalRx/Tx changed since the last DB flush.
type peerTrafficState struct {
	lastSeenRx int64
	lastSeenTx int64
	totalRx    int64
	totalTx    int64
	dirty      bool
}

// TunnelInterface represents a single WireGuard or AmneziaWG tunnel interface.
type TunnelInterface struct {
	reloadMu  sync.Mutex   // serializes Reload/Restart — concurrent syncconf = kernel deadlock (FIX-8, FIX-9)
	peersMu   sync.RWMutex // protects peers map: written by AddPeer/Remove, read by GetStatus goroutine
	trafficMu sync.Mutex   // protects trafficState map

	// ── Persisted (SQLite interfaces table) ──────────────────────────────────
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Address       string             `json:"address"` // CIDR e.g. "10.8.0.1/24"
	ListenPort    int                `json:"listenPort"`
	Protocol      string             `json:"protocol"` // WireGuard 1.0, AWG 2.0, or AWG 3.1
	Enabled       bool               `json:"enabled"`
	DisableRoutes bool               `json:"disableRoutes"` // Table = off (S2S / PBR setups)
	NatDisabled   bool               `json:"natDisabled"`   // when true, PostUp omits MASQUERADE
	PublicHost    string             `json:"publicHost"`    // per-interface endpoint override (e.g. transit server IP)
	DNS           string             `json:"dns"`           // per-interface DNS override; empty = use global setting
	MTU           int                `json:"mtu"`           // 0 = use global setting; >0 = per-interface override
	MSS           int                `json:"mss"`           // -1 = clamp-mss-to-pmtu; 0 = disabled; >0 = set-mss value
	Uplink        bool               `json:"uplink"`        // true when created via Import .conf (connects OUT to remote server)
	PrivateKey    string             `json:"-"`             // never exposed in API responses
	PublicKey     string             `json:"publicKey"`
	AWG2          *peer.AWG2Settings `json:"settings"` // nil for wireguard-1.0
	CreatedAt     string             `json:"createdAt"`

	// ── Runtime (in-memory, not persisted) ───────────────────────────────────
	peers        map[string]*peer.Peer        // keyed by peer.ID; protected by peersMu
	trafficState map[string]*peerTrafficState // keyed by peer.ID; protected by trafficMu
}

// InterfaceInput is the payload for creating a new interface.
type InterfaceInput struct {
	ID            string
	Name          string
	Address       string // CIDR e.g. "10.8.0.1/24"
	ListenPort    int
	Protocol      string // "wireguard-1.0" | "amneziawg-2.0"
	DisableRoutes bool
	PrivateKey    string             // must be pre-generated by caller
	PublicKey     string             // derived from PrivateKey
	AWG2          *peer.AWG2Settings // nil for wireguard-1.0
	DNS           string             // per-interface DNS override; empty = use global
}

// InterfaceUpdate holds the mutable fields changeable via PATCH.
// nil pointer = do not change that field.
type InterfaceUpdate struct {
	Name          *string
	Address       *string
	ListenPort    *int
	DisableRoutes *bool
	NatDisabled   *bool
	DNS           *string            // per-interface DNS override; empty string = clear (use global)
	PublicHost    *string            // per-interface endpoint override; empty string = clear (use global)
	MTU           *int               // 0 = use global; >0 = per-interface override
	MSS           *int               // -1=auto (clamp-mss-to-pmtu); 0=off; >0=manual set-mss value
	AWG2          *peer.AWG2Settings // non-nil = replace all AWG2 params
}

// InterfaceExport is the response body for export-params (S2S interconnect flow).
type InterfaceExport struct {
	Name         string `json:"name"`
	PublicKey    string `json:"publicKey"`
	Endpoint     string `json:"endpoint"`
	Address      string `json:"address"`
	Protocol     string `json:"protocol"`
	AllowedIPs   string `json:"allowedIPs,omitempty"`   // "0.0.0.0/0" for DisableRoutes ifaces
	PresharedKey string `json:"presharedKey,omitempty"` // included only if PSK already exists
}

// ── Load / Save / Create / Delete ────────────────────────────────────────────

// LoadInterface reads one interface from SQLite and populates its peer cache.
func LoadInterface(id string) (*TunnelInterface, error) {
	t, err := scanInterface(id)
	if err != nil {
		return nil, err
	}
	if err := t.LoadPeers(); err != nil {
		return nil, fmt.Errorf("load peers for %s: %w", id, err)
	}
	return t, nil
}

// ListInterfaceIDs returns all interface IDs ordered by created_at.
// Used by InterfaceManager at startup.
func ListInterfaceIDs() ([]string, error) {
	rows, err := db.DB().Query(`SELECT id FROM interfaces ORDER BY created_at`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var ids []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	return ids, rows.Err()
}

// Create inserts a new interface into SQLite and returns it.
// Does NOT start the interface; call Start() explicitly.
func Create(inp InterfaceInput) (*TunnelInterface, error) {
	t := &TunnelInterface{
		ID:            inp.ID,
		Name:          inp.Name,
		Address:       inp.Address,
		ListenPort:    inp.ListenPort,
		Protocol:      inp.Protocol,
		Enabled:       false,
		DisableRoutes: inp.DisableRoutes,
		DNS:           strings.TrimSpace(inp.DNS),
		PrivateKey:    inp.PrivateKey,
		PublicKey:     inp.PublicKey,
		AWG2:          inp.AWG2,
		CreatedAt:     time.Now().UTC().Format(time.RFC3339),
		peers:         make(map[string]*peer.Peer),
	}
	if err := t.save(); err != nil {
		return nil, err
	}
	return t, nil
}

// Update applies non-nil fields from upd, persists, regenerates config, and hot-reloads.
//
// Fields that require a full Restart() (wg-quick down → up) instead of Reload() (syncconf):
//   - Address:     syncconf does not update kernel routing table (ip route add/del)
//   - ListenPort:  syncconf does not rebind the UDP socket
//   - NatDisabled: syncconf skips PostUp/PostDown, so MASQUERADE changes are not applied
//   - MTU:         syncconf does not run `ip link set dev wgX mtu N`
//   - DisableRoutes: changes Table=off, which affects routing setup in PostUp
//
// All other fields (Name, PublicHost, AWG2 params) are safe for hot-reload via syncconf.
func (t *TunnelInterface) Update(upd InterfaceUpdate) error {
	addressChanged := upd.Address != nil && strings.TrimSpace(*upd.Address) != t.Address
	listenPortChanged := upd.ListenPort != nil && *upd.ListenPort != t.ListenPort
	natDisabledChanged := upd.NatDisabled != nil && *upd.NatDisabled != t.NatDisabled
	mtuChanged := upd.MTU != nil && *upd.MTU != t.MTU
	mssChanged := upd.MSS != nil && *upd.MSS != t.MSS
	disableRoutesChanged := upd.DisableRoutes != nil && *upd.DisableRoutes != t.DisableRoutes

	if upd.Name != nil {
		t.Name = strings.TrimSpace(*upd.Name)
	}
	if upd.Address != nil {
		t.Address = strings.TrimSpace(*upd.Address)
	}
	if upd.ListenPort != nil {
		t.ListenPort = *upd.ListenPort
	}
	if upd.DisableRoutes != nil {
		t.DisableRoutes = *upd.DisableRoutes
	}
	if upd.NatDisabled != nil {
		t.NatDisabled = *upd.NatDisabled
	}
	if upd.DNS != nil {
		t.DNS = strings.TrimSpace(*upd.DNS)
	}
	if upd.PublicHost != nil {
		t.PublicHost = strings.TrimSpace(*upd.PublicHost)
	}
	if upd.MTU != nil {
		t.MTU = *upd.MTU
	}
	if upd.MSS != nil {
		t.MSS = *upd.MSS
	}
	if upd.AWG2 != nil {
		if err := awgparams.Validate(t.Protocol, upd.AWG2); err != nil {
			return err
		}
		t.AWG2 = upd.AWG2
	}
	if err := t.save(); err != nil {
		return err
	}
	if err := t.RegenerateConfig(); err != nil {
		return err
	}
	if t.Enabled {
		needsRestart := addressChanged || listenPortChanged || natDisabledChanged ||
			mtuChanged || mssChanged || disableRoutesChanged
		if needsRestart {
			// Full wg-quick down → up required to apply kernel-level changes.
			// reloadMu must be held: concurrent awg syncconf + awg-quick up = deadlock (FIX-8/9).
			go func() {
				t.reloadMu.Lock()
				defer t.reloadMu.Unlock()
				if err := t.Restart(); err != nil {
					log.Printf("tunnel: Update %s: restart failed: %v", t.ID, err)
				}
			}()
		} else {
			t.Reload() // hot-reload via syncconf — safe for Name, PublicHost, AWG2 params
		}
	}
	return nil
}

// Delete stops the interface, removes all its peers from SQLite, deletes the
// interface row, and removes the wg-quick config file from disk.
func (t *TunnelInterface) Delete() error {
	if t.Enabled {
		if err := t.Stop(); err != nil {
			log.Printf("tunnel: delete %s: stop failed (continuing): %v", t.ID, err)
		}
	}

	// Remove all peers from SQLite.
	t.peersMu.RLock()
	peerIDs := make([]string, 0, len(t.peers))
	for id := range t.peers {
		peerIDs = append(peerIDs, id)
	}
	t.peersMu.RUnlock()

	for _, pid := range peerIDs {
		if err := peer.DeletePeer(pid); err != nil {
			log.Printf("tunnel: delete %s: remove peer %s: %v", t.ID, pid, err)
		}
	}

	if _, err := db.DB().Exec(`DELETE FROM interfaces WHERE id = ?`, t.ID); err != nil {
		return fmt.Errorf("delete interface %s: %w", t.ID, err)
	}
	// Config file is best-effort (may not exist if interface was never started).
	_ = os.Remove(fmt.Sprintf("/etc/amnezia/amneziawg/%s.conf", t.ID))

	log.Printf("tunnel: interface %s deleted", t.ID)
	return nil
}

// save upserts the TunnelInterface row in SQLite.
// Called internally after every state change (Start, Stop, Update).
func (t *TunnelInterface) save() error {
	// Flatten AmneziaWG settings into nullable columns (nil becomes SQL NULL).
	var jc, jmin, jmax, s1, s2, s3, s4 interface{}
	var h1, h2, h3, h4 interface{}
	var i1, i2, i3, i4, i5 interface{}
	var headerProtectionKey, contentPaddingAddition, rekeyAfterTime, rekeyTimeout interface{}
	var rejectAfterTime, keepaliveTimeout, maxHandshakeAttempts, randomTrailers, disableCookies interface{}
	if t.AWG2 != nil {
		a := t.AWG2
		jc, jmin, jmax = a.Jc, a.Jmin, a.Jmax
		s1, s2, s3, s4 = a.S1, a.S2, a.S3, a.S4
		h1, h2, h3, h4 = a.H1, a.H2, a.H3, a.H4
		i1, i2, i3, i4, i5 = a.I1, a.I2, a.I3, a.I4, a.I5
		if t.Protocol == "amneziawg-3.1" {
			headerProtectionKey, contentPaddingAddition = a.HeaderProtectionKey, a.ContentPaddingAddition
			rekeyAfterTime, rekeyTimeout = a.RekeyAfterTime, a.RekeyTimeout
			rejectAfterTime, keepaliveTimeout = a.RejectAfterTime, a.KeepaliveTimeout
			maxHandshakeAttempts = a.MaxHandshakeAttempts
			if a.RandomTrailers != nil {
				randomTrailers = boolInt(*a.RandomTrailers)
			}
			if a.DisableCookies != nil {
				disableCookies = boolInt(*a.DisableCookies)
			}
		}
	}

	_, err := db.DB().Exec(`
		INSERT INTO interfaces
			(id, name, address, listen_port, protocol, enabled, disable_routes, nat_disabled,
			 dns, public_host, mtu, mss, uplink, private_key, public_key,
			 jc, jmin, jmax, s1, s2, s3, s4, h1, h2, h3, h4,
			 i1, i2, i3, i4, i5, header_protection_key, content_padding_addition,
			 rekey_after_time, rekey_timeout, reject_after_time, keepalive_timeout,
			 max_handshake_attempts, random_trailers, disable_cookies, created_at)
		VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
		ON CONFLICT(id) DO UPDATE SET
			name=excluded.name, address=excluded.address,
			listen_port=excluded.listen_port, protocol=excluded.protocol,
			enabled=excluded.enabled, disable_routes=excluded.disable_routes,
			nat_disabled=excluded.nat_disabled, dns=excluded.dns,
			public_host=excluded.public_host,
			mtu=excluded.mtu, mss=excluded.mss, uplink=excluded.uplink,
			private_key=excluded.private_key, public_key=excluded.public_key,
			jc=excluded.jc, jmin=excluded.jmin, jmax=excluded.jmax,
			s1=excluded.s1, s2=excluded.s2, s3=excluded.s3, s4=excluded.s4,
			h1=excluded.h1, h2=excluded.h2, h3=excluded.h3, h4=excluded.h4,
			i1=excluded.i1, i2=excluded.i2, i3=excluded.i3, i4=excluded.i4, i5=excluded.i5,
			header_protection_key=excluded.header_protection_key,
			content_padding_addition=excluded.content_padding_addition,
			rekey_after_time=excluded.rekey_after_time, rekey_timeout=excluded.rekey_timeout,
			reject_after_time=excluded.reject_after_time, keepalive_timeout=excluded.keepalive_timeout,
			max_handshake_attempts=excluded.max_handshake_attempts,
			random_trailers=excluded.random_trailers, disable_cookies=excluded.disable_cookies`,
		t.ID, t.Name, t.Address, t.ListenPort, t.Protocol,
		boolInt(t.Enabled), boolInt(t.DisableRoutes), boolInt(t.NatDisabled),
		t.DNS, t.PublicHost, t.MTU, t.MSS, boolInt(t.Uplink), t.PrivateKey, t.PublicKey,
		jc, jmin, jmax, s1, s2, s3, s4,
		h1, h2, h3, h4,
		i1, i2, i3, i4, i5,
		headerProtectionKey, contentPaddingAddition, rekeyAfterTime, rekeyTimeout,
		rejectAfterTime, keepaliveTimeout, maxHandshakeAttempts, randomTrailers, disableCookies,
		t.CreatedAt,
	)
	return err
}

// ── Peer cache ────────────────────────────────────────────────────────────────

// LoadPeers fetches all peers for this interface from SQLite into the in-memory map.
// Also initialises trafficState from persisted total_rx/total_tx (migration v11)
// so that lifetime totals survive container restarts.
// Called at startup; kept in sync by AddPeer / UpdatePeer / RemovePeer.
func (t *TunnelInterface) LoadPeers() error {
	ps, err := peer.GetPeers(t.ID)
	if err != nil {
		return err
	}
	t.peersMu.Lock()
	t.peers = make(map[string]*peer.Peer, len(ps))
	for i := range ps {
		t.peers[ps[i].ID] = &ps[i]
	}
	t.peersMu.Unlock()

	// Initialise trafficState from DB totals.
	// lastSeenRx/Tx starts at 0: after container restart the kernel counter
	// resets to 0 too, so the first delta is always 0 (no phantom traffic spike).
	t.trafficMu.Lock()
	t.trafficState = make(map[string]*peerTrafficState, len(ps))
	for i := range ps {
		t.trafficState[ps[i].ID] = &peerTrafficState{
			totalRx: ps[i].TotalRx,
			totalTx: ps[i].TotalTx,
		}
	}
	t.trafficMu.Unlock()
	return nil
}

// GetPeer returns the in-memory peer by ID, or nil if not found.
func (t *TunnelInterface) GetPeer(id string) *peer.Peer {
	t.peersMu.RLock()
	defer t.peersMu.RUnlock()
	return t.peers[id]
}

// ReloadPeerFromDB re-reads a single peer from SQLite and replaces the
// in-memory cached copy. Use after a direct DB write that bypasses
// peer.UpdatePeer (e.g. SavePrivateKey) so computed fields like
// DownloadableConfig stay in sync with the persisted row.
func (t *TunnelInterface) ReloadPeerFromDB(id string) (*peer.Peer, error) {
	fresh, err := peer.GetPeer(id)
	if err != nil {
		return nil, err
	}
	if fresh == nil {
		return nil, nil
	}
	t.replaceCachedPeer(fresh)
	return fresh, nil
}

// ConsumePeerOneTimeLink atomically clears a persisted one-time token and then
// refreshes the in-memory cache. Once consumed, a cache refresh failure must not
// turn the successful redemption into an unretryable HTTP error.
func (t *TunnelInterface) ConsumePeerOneTimeLink(id, token string) (bool, error) {
	consumed, err := peer.ConsumeOneTimeLink(id, token)
	if err != nil || !consumed {
		return consumed, err
	}
	if _, reloadErr := t.ReloadPeerFromDB(id); reloadErr != nil {
		log.Printf("tunnel: refresh peer %s after one-time token consumption: %v", id, reloadErr)
	}
	return true, nil
}

// replaceCachedPeer restores the cache invariant that a peer is stored only
// under its own ID. It also removes stale aliases left by older releases.
func (t *TunnelInterface) replaceCachedPeer(updated *peer.Peer) {
	if updated == nil {
		return
	}
	t.peersMu.Lock()
	defer t.peersMu.Unlock()
	if t.peers == nil {
		t.peers = make(map[string]*peer.Peer)
	}
	for key, cached := range t.peers {
		if key == updated.ID {
			continue
		}
		if cached == nil || cached.ID == updated.ID ||
			(updated.PublicKey != "" && cached.PublicKey == updated.PublicKey) {
			delete(t.peers, key)
		}
	}
	t.peers[updated.ID] = updated
}

// GetAllPeers returns a snapshot of all in-memory peers.
func (t *TunnelInterface) GetAllPeers() []*peer.Peer {
	t.peersMu.RLock()
	defer t.peersMu.RUnlock()
	out := make([]*peer.Peer, 0, len(t.peers))
	for _, p := range t.peers {
		out = append(out, p)
	}
	// Go map iteration is non-deterministic — sort by CreatedAt so the frontend
	// receives peers in a stable order on every poll tick.
	// Secondary sort by ID (UUID) guarantees stability when multiple peers share
	// the same CreatedAt timestamp (e.g. batch import creates many peers per second).
	sort.Slice(out, func(i, j int) bool {
		if out[i].CreatedAt != out[j].CreatedAt {
			return out[i].CreatedAt < out[j].CreatedAt
		}
		return out[i].ID < out[j].ID
	})
	return out
}

// PeerCount returns the number of peers in the cache.
func (t *TunnelInterface) PeerCount() int {
	t.peersMu.RLock()
	defer t.peersMu.RUnlock()
	return len(t.peers)
}

// ── Peer CRUD ─────────────────────────────────────────────────────────────────

// peerEffectiveRateLimits returns the rate limits that should be applied via tc
// for the given peer. If the peer has individual limits, they take precedence.
// Otherwise the group's limits are returned. group may be nil.
func peerEffectiveRateLimits(peerRateDown, peerRateUp int, group *aliases.Alias) (rateDown, rateUp int) {
	if peerRateDown > 0 || peerRateUp > 0 {
		return peerRateDown, peerRateUp
	}
	if group != nil {
		return group.RateDown, group.RateUp
	}
	return 0, 0
}

// AddPeer creates a new peer in SQLite, updates the in-memory cache,
// regenerates the wg-quick config, and applies the peer to the kernel.
func (t *TunnelInterface) AddPeer(inp peer.PeerInput) (*peer.Peer, error) {
	// Auto-allocate the hub-side IP before inserting (needs in-memory peer map).
	if inp.AutoAllocateIP {
		ip, err := t.AutoAllocateIP()
		if err != nil {
			return nil, fmt.Errorf("auto-allocate IP: %w", err)
		}
		inp.AllowedIPs = ip
		inp.AutoAllocateIP = false
	}

	// Generate key triplet if requested (protocol-aware: wg vs awg).
	if inp.GenerateKeys {
		keys, err := peer.GenerateKeys(t.syncBin())
		if err != nil {
			return nil, fmt.Errorf("generate keys: %w", err)
		}
		inp.PrivateKey = keys.PrivateKey
		inp.PublicKey = keys.PublicKey
		inp.PresharedKey = keys.PresharedKey
		inp.GenerateKeys = false
	}

	// Interconnect peers always need a PSK for mutual authentication.
	// If none was provided (first importer in S2S workflow), generate one now.
	// The importer exports their params with this PSK so the remote side can
	// import it and the two ends end up with a matching PSK.
	if inp.PeerType == "interconnect" && inp.PresharedKey == "" {
		psk, err := peer.GeneratePSK(t.syncBin())
		if err != nil {
			return nil, fmt.Errorf("generate PSK for interconnect peer: %w", err)
		}
		inp.PresharedKey = psk
	}

	// Derive peer tunnel address from AllowedIPs when not set.
	// Use the mask from AllowedIPs itself (e.g. /32 for client peers).
	// The interface mask is NOT used here — it would show /24 for client peers
	// whose AllowedIPs is already /32, which is confusing in the UI.
	if inp.Address == "" && inp.AllowedIPs != "" {
		firstCIDR := strings.TrimSpace(strings.Split(inp.AllowedIPs, ",")[0])
		peerIP := strings.SplitN(firstCIDR, "/", 2)[0]
		if peerIP != "" && peerIP != "0.0.0.0" {
			mask := "32"
			if parts := strings.SplitN(firstCIDR, "/", 2); len(parts) == 2 {
				mask = parts[1]
			}
			inp.Address = peerIP + "/" + mask
		}
	}

	// Validate fields that will be passed to shell commands (command injection prevention).
	if inp.PublicKey != "" {
		if err := validate.WGKey(inp.PublicKey); err != nil {
			return nil, fmt.Errorf("invalid public key: %w", err)
		}
	}
	if inp.PresharedKey != "" {
		if err := validate.WGKey(inp.PresharedKey); err != nil {
			return nil, fmt.Errorf("invalid preshared key: %w", err)
		}
	}
	if inp.AllowedIPs != "" {
		if err := validate.CIDR(inp.AllowedIPs); err != nil {
			return nil, fmt.Errorf("invalid allowed IPs: %w", err)
		}
	}
	if inp.Endpoint != "" {
		if err := validate.Endpoint(inp.Endpoint); err != nil {
			return nil, fmt.Errorf("invalid endpoint: %w", err)
		}
	}
	// PrivateKey is written verbatim into the .conf file — validate to prevent
	// newline injection (e.g. "\nPostUp = <cmd>") that would execute on wg-quick up.
	// Empty is allowed: interconnect peers have no server-side private key (HIGH-3).
	if inp.PrivateKey != "" {
		if err := validate.WGKey(inp.PrivateKey); err != nil {
			return nil, fmt.Errorf("invalid private key: %w", err)
		}
	}
	if inp.ClientAllowedIPs != "" {
		if err := validate.CIDR(inp.ClientAllowedIPs); err != nil {
			return nil, fmt.Errorf("invalid client allowed IPs: %w", err)
		}
	}
	if inp.Address != "" {
		if err := validate.CIDR(inp.Address); err != nil {
			return nil, fmt.Errorf("invalid address: %w", err)
		}
	}

	p, err := peer.CreatePeer(t.ID, inp)
	if err != nil {
		return nil, err
	}

	t.replaceCachedPeer(p)

	// Initialise traffic state for new peer (starts at zero, no prior traffic).
	t.trafficMu.Lock()
	if t.trafficState == nil {
		t.trafficState = make(map[string]*peerTrafficState)
	}
	t.trafficState[p.ID] = &peerTrafficState{}
	t.trafficMu.Unlock()

	if err := t.RegenerateConfig(); err != nil {
		return p, err
	}
	if t.Enabled {
		t.KernelSetPeer(p)
		// Apply group rate limits for new client peers with no individual limits.
		if p.PeerType == "client" && p.AllowedIPs != "" && p.RateDown == 0 && p.RateUp == 0 && p.GroupID != "" {
			if am := aliases.Get(); am != nil {
				if g, err := am.GetByID(p.GroupID); err == nil {
					if rd, ru := peerEffectiveRateLimits(0, 0, g); rd > 0 || ru > 0 {
						tc.EnsureQdisc(t.ID)
						tc.Apply(t.ID, p.AllowedIPs, rd, ru, t.kernelMTU())
					}
				}
			}
		}
	}
	return p, nil
}

// UpdatePeer applies upd to the peer in SQLite and in-memory cache.
// Reloads kernel config only if WireGuard-relevant fields changed.
func (t *TunnelInterface) UpdatePeer(peerID string, upd peer.PeerUpdate) (*peer.Peer, error) {
	// Capture old peer state before update to detect changes that need kernel sync.
	var oldPeer *peer.Peer
	if old := t.GetPeer(peerID); old != nil {
		copy := *old
		oldPeer = &copy
	}

	updated, err := peer.UpdatePeer(peerID, upd)
	if err != nil {
		return nil, err
	}

	t.replaceCachedPeer(updated)

	// Only reload the kernel when fields that appear in [Peer] config sections change.
	wgFields := upd.Enabled != nil || upd.AllowedIPs != nil ||
		upd.Endpoint != nil || upd.PersistentKeepalive != nil

	if wgFields {
		if err := t.RegenerateConfig(); err != nil {
			return updated, err
		}
		if t.Enabled {
			if updated.Enabled {
				t.KernelSetPeer(updated)
			} else {
				t.KernelRemovePeer(peerID)
			}
		}
	}

	// Apply/remove tc bandwidth limits when rate values actually changed.
	// Check actual before/after values, not just upd fields — the renewal path
	// in peer.UpdatePeer may zero out RateDown/RateUp without setting upd.RateDown/Up.
	oldRateDown, oldRateUp := 0, 0
	if oldPeer != nil {
		oldRateDown = oldPeer.RateDown
		oldRateUp = oldPeer.RateUp
	}
	if t.Enabled && updated.PeerType == "client" &&
		(updated.RateDown != oldRateDown || updated.RateUp != oldRateUp) {
		if updated.RateDown > 0 || updated.RateUp > 0 {
			tc.EnsureQdisc(t.ID)
			tc.Apply(t.ID, updated.AllowedIPs, updated.RateDown, updated.RateUp, t.kernelMTU())
		} else {
			tc.Remove(t.ID, updated.AllowedIPs)
		}
	}

	// Rebuild client-group ipsets when group changes (covers both API and expiry-checker paths).
	// Compare actual before/after group values — renewal path changes GroupID without setting upd.GroupID.
	oldGroupID := ""
	if oldPeer != nil {
		oldGroupID = oldPeer.GroupID
	}
	if updated.PeerType == "client" && oldGroupID != updated.GroupID {
		if am := aliases.Get(); am != nil {
			if oldGroupID != "" {
				if err := am.RebuildGroupIPSet(oldGroupID); err != nil {
					log.Printf("tunnel: UpdatePeer: rebuild old group ipset %s: %v", oldGroupID, err)
				}
			}
			if updated.GroupID != "" {
				if err := am.RebuildGroupIPSet(updated.GroupID); err != nil {
					log.Printf("tunnel: UpdatePeer: rebuild new group ipset %s: %v", updated.GroupID, err)
				}
			}
			// Apply group rate limits when peer has no individual limits.
			if t.Enabled && updated.AllowedIPs != "" && updated.RateDown == 0 && updated.RateUp == 0 {
				var g *aliases.Alias
				if updated.GroupID != "" {
					g, _ = am.GetByID(updated.GroupID)
				}
				if rd, ru := peerEffectiveRateLimits(0, 0, g); rd > 0 || ru > 0 {
					tc.EnsureQdisc(t.ID)
					tc.Apply(t.ID, updated.AllowedIPs, rd, ru, t.kernelMTU())
				} else {
					tc.Remove(t.ID, updated.AllowedIPs)
				}
			}
		}
	}

	return updated, nil
}

// RemovePeer deletes the peer from SQLite, removes it from the cache,
// regenerates config, and removes it from the running kernel.
func (t *TunnelInterface) RemovePeer(peerID string) error {
	// Capture peer data before deletion (needed for tc cleanup).
	t.peersMu.RLock()
	removed := t.peers[peerID]
	t.peersMu.RUnlock()

	if err := peer.DeletePeer(peerID); err != nil {
		return err
	}

	t.peersMu.Lock()
	delete(t.peers, peerID)
	t.peersMu.Unlock()

	t.trafficMu.Lock()
	delete(t.trafficState, peerID)
	t.trafficMu.Unlock()

	if err := t.RegenerateConfig(); err != nil {
		return err
	}
	if t.Enabled {
		t.KernelRemovePeer(peerID)
		// Remove tc rules for the deleted peer (client peers only).
		if removed != nil && removed.PeerType == "client" {
			tc.Remove(t.ID, removed.AllowedIPs)
		}
	}
	return nil
}

// ── Lifecycle ─────────────────────────────────────────────────────────────────

// quickBin returns the wg-quick equivalent for this interface's protocol (FIX-7).
func (t *TunnelInterface) quickBin() string {
	if isAWGProtocol(t.Protocol) {
		return "awg-quick"
	}
	return "wg-quick"
}

// syncBin returns the wg equivalent for this interface's protocol (FIX-7).
func (t *TunnelInterface) syncBin() string {
	if isAWGProtocol(t.Protocol) {
		return "awg"
	}
	return "wg"
}

// isUserspaceMode reports whether AmneziaWG is running in userspace mode.
// Userspace mode is active when WG_QUICK_USERSPACE_IMPLEMENTATION=amneziawg-go.
// In userspace mode: awg syncconf is stable (no kernel deadlock), so
// KernelRemovePeer can use Reload() instead of full Restart().
func isUserspaceMode() bool {
	return os.Getenv("WG_QUICK_USERSPACE_IMPLEMENTATION") == "amneziawg-go"
}

// Start regenerates the config file and brings up the interface (FIX-2).
//
// With --network host, the WireGuard interface lives in the host kernel and
// survives docker stop/start. Three failure modes are handled:
//
//   - "already exists": cycle down→up so PostUp (iptables MASQUERADE) re-executes.
//   - "Address in use": flush stale kernel routes left by a previous interface,
//     then retry.
func (t *TunnelInterface) Start() error {
	// Always regenerate before up — ensures PostUp/PostDown are current (FIX-2).
	if err := t.RegenerateConfig(); err != nil {
		return fmt.Errorf("start %s: regenerate config: %w", t.ID, err)
	}

	_, err := util.ExecDefault(fmt.Sprintf("%s up %s", t.quickBin(), t.ID))
	if err != nil {
		msg := err.Error()
		switch {
		case strings.Contains(msg, "already exists"):
			// Interface survived docker restart in --network host mode.
			// Cycling down→up re-executes PostUp (iptables MASQUERADE, etc.).
			log.Printf("tunnel: %s already exists — cycling down/up to apply PostUp", t.ID)
			if _, e := util.ExecDefault(fmt.Sprintf("%s down %s", t.quickBin(), t.ID)); e != nil {
				log.Printf("tunnel: %s down (cycle) error (continuing): %v", t.ID, e)
			}
			if _, e := util.ExecDefault(fmt.Sprintf("%s up %s", t.quickBin(), t.ID)); e != nil {
				return fmt.Errorf("start %s after cycle: %w", t.ID, e)
			}
		case strings.Contains(msg, "Address in use"):
			// Stale route from a previous wg interface left in the kernel.
			// Flush and retry once.
			log.Printf("tunnel: %s address in use — flushing stale routes and retrying", t.ID)
			subnet := cidrToSubnet(t.Address)
			util.ExecSilent(fmt.Sprintf("ip route del %s 2>/dev/null || true", subnet))
			util.ExecSilent(fmt.Sprintf("ip route del %s table local 2>/dev/null || true", subnet))
			if _, e := util.ExecDefault(fmt.Sprintf("%s up %s", t.quickBin(), t.ID)); e != nil {
				return fmt.Errorf("start %s after flush: %w", t.ID, e)
			}
		default:
			return fmt.Errorf("start %s: %w", t.ID, err)
		}
	}

	t.Enabled = true
	if err := t.save(); err != nil {
		return err
	}

	// Restore per-client bandwidth limits after interface comes up.
	go t.restoreTCLimits()

	return nil
}

// restoreTCLimits rebuilds tc rules for all client peers with rate limits.
// Called asynchronously after Start() so it doesn't block the interface startup.
// kernelMTU reads the actual MTU of this interface from kernel sysfs.
// Returns 0 if the interface is not yet up or the file is unreadable.
func (t *TunnelInterface) kernelMTU() int {
	data, err := os.ReadFile("/sys/class/net/" + t.ID + "/mtu")
	if err != nil {
		return 0
	}
	n, err := strconv.Atoi(strings.TrimSpace(string(data)))
	if err != nil {
		return 0
	}
	return n
}

func (t *TunnelInterface) restoreTCLimits() {
	am := aliases.Get()

	// Pre-load group rate limits to avoid repeated DB lookups.
	groupLimits := map[string][2]int{} // groupID → [rateDown, rateUp]
	if am != nil {
		if groups, err := am.GetClientGroups(); err == nil {
			for _, g := range groups {
				if g.RateDown > 0 || g.RateUp > 0 {
					groupLimits[g.ID] = [2]int{g.RateDown, g.RateUp}
				}
			}
		}
	}

	t.peersMu.RLock()
	var limits []tc.PeerLimit
	for _, p := range t.peers {
		if p.PeerType != "client" {
			continue
		}
		rd, ru := p.RateDown, p.RateUp
		// Fall back to group rate limits when peer has no individual limits.
		if rd == 0 && ru == 0 {
			if gl, ok := groupLimits[p.GroupID]; ok {
				rd, ru = gl[0], gl[1]
			}
		}
		if rd <= 0 && ru <= 0 {
			continue
		}
		limits = append(limits, tc.PeerLimit{
			IP:       p.AllowedIPs,
			RateDown: rd,
			RateUp:   ru,
		})
	}
	t.peersMu.RUnlock()
	tc.RestoreAll(t.ID, limits, t.kernelMTU())
}

// Stop brings down the interface and ignores benign errors (FIX-3):
//   - interface already stopped ("not a WireGuard/AmneziaWG interface")
//   - iptables rule not found at PostDown time ("Bad rule", "does a matching rule exist")
//
// Flushes traffic totals to DB before bringing the interface down so that the
// kernel counters (which reset on wg-quick down) are not lost.
func (t *TunnelInterface) Stop() error {
	t.FlushTrafficTotals()
	_, err := util.ExecDefault(fmt.Sprintf("%s down %s", t.quickBin(), t.ID))
	if err != nil {
		ignored := []string{
			"is not a WireGuard interface",
			"is not an AmneziaWG interface",
			"iptables: Bad rule",
			"does a matching rule exist",
		}
		msg := err.Error()
		benign := false
		for _, s := range ignored {
			if strings.Contains(msg, s) {
				benign = true
				break
			}
		}
		if !benign {
			return fmt.Errorf("stop %s: %w", t.ID, err)
		}
	}

	t.Enabled = false
	return t.save()
}

// Restart stops and starts the interface.
func (t *TunnelInterface) Restart() error {
	if err := t.Stop(); err != nil {
		return err
	}
	return t.Start()
}

// Reload enqueues a hot-reload (awg/wg syncconf) in a background goroutine.
// Concurrent Reload/Restart calls are serialized by reloadMu so that the kernel
// never receives two concurrent syncconf calls on the same device (deadlock risk).
func (t *TunnelInterface) Reload() {
	go func() {
		t.reloadMu.Lock()
		defer t.reloadMu.Unlock()
		if err := t.doReload(); err != nil {
			log.Printf("tunnel: reload %s failed: %v", t.ID, err)
		}
	}()
}

// syncconfTimeout is the deadline for `awg/wg syncconf`.
// Mirrors amneziawg-installer v5.7.5 mitigation for upstream kernel deadlock #146:
// if the AWG kernel module hangs during syncconf, kill it after 10s and fall back
// to a full interface restart instead of hanging indefinitely.
const syncconfTimeout = 10 * time.Second

// doReload executes `<syncBin> syncconf <id> <(<quickBin> strip <id>)`.
// Uses bash process substitution — works because util.Exec runs via `bash -c`.
// Must be called with reloadMu held.
//
// On timeout or error (AWG kernel deadlock #146): falls back to full Restart().
// Restart() itself holds no locks, so calling it here (while reloadMu is held)
// is safe — any subsequent Reload() goroutine will simply queue behind reloadMu.
func (t *TunnelInterface) doReload() error {
	cmd := fmt.Sprintf("%s syncconf %s <(%s strip %s)",
		t.syncBin(), t.ID, t.quickBin(), t.ID)
	if _, err := util.Exec(cmd, syncconfTimeout, true); err != nil {
		// syncconf timed out or failed — likely AWG kernel module deadlock (#146).
		// Fall back to full down→up restart to recover a clean kernel state.
		log.Printf("tunnel: %s syncconf failed (%v) — falling back to full restart", t.ID, err)
		if restartErr := t.Restart(); restartErr != nil {
			return fmt.Errorf("syncconf failed and fallback restart also failed: %w", restartErr)
		}
		log.Printf("tunnel: %s recovered via full restart after syncconf failure", t.ID)
		return nil
	}
	log.Printf("tunnel: %s hot-reloaded (syncconf)", t.ID)
	return nil
}

// ── Kernel sync ───────────────────────────────────────────────────────────────

// KernelSetPeer applies a peer addition/update to the running kernel (FIX-9).
//
//   - AmneziaWG: calls Reload() (awg syncconf via quickBin strip).
//     `awg set peer` is unstable in the AWG kernel module (10-15+ seconds,
//     leaves kernel in bad state). syncconf is atomic and reliable.
//   - WireGuard 1.0: runs `wg set peer <key> …` which is fast and reliable.
//
// Fire-and-forget: returns immediately; work runs in background goroutine.
func (t *TunnelInterface) KernelSetPeer(p *peer.Peer) {
	if !t.Enabled {
		return
	}
	if isAWGProtocol(t.Protocol) {
		t.Reload() // Reload already serializes via reloadMu
		return
	}

	// WireGuard 1.0: wg set peer is reliable, run under reloadMu for safety.
	go func() {
		t.reloadMu.Lock()
		defer t.reloadMu.Unlock()

		// Write PSK to a temp file (wg set peer preshared-key takes a file path).
		var pskFile string
		if p.PresharedKey != "" {
			pskFile = fmt.Sprintf("/tmp/%s-psk-%s", t.ID, p.ID)
			if err := os.WriteFile(pskFile, []byte(p.PresharedKey+"\n"), 0600); err != nil {
				log.Printf("tunnel: KernelSetPeer %s: write psk file: %v", p.ID, err)
				return
			}
			defer os.Remove(pskFile)
		}

		cmd := fmt.Sprintf("%s set %s peer %s", t.syncBin(), t.ID, p.PublicKey)
		if pskFile != "" {
			cmd += " preshared-key " + pskFile
		}
		if p.AllowedIPs != "" {
			cmd += " allowed-ips " + p.AllowedIPs
		}
		if p.Endpoint != "" {
			cmd += " endpoint " + p.Endpoint
		}
		if p.PersistentKeepalive > 0 {
			cmd += " persistent-keepalive " + strconv.Itoa(p.PersistentKeepalive)
		}
		if _, err := util.ExecDefault(cmd); err != nil {
			log.Printf("tunnel: KernelSetPeer %s failed: %v", p.ID, err)
		}
	}()
}

// KernelRemovePeer removes a peer from the running kernel (FIX-8).
//
// Kernel mode: uses full Restart() (down + up).
//
//	Both `awg set peer remove` and `awg syncconf` deadlock in the AWG kernel module
//	after ~3–5 add/remove cycles. Restart is the safe alternative.
//	Downside: per-peer transfer stats are reset on each restart.
//
// Userspace mode: uses Reload() (awg syncconf).
//
//	The userspace daemon has no kernel deadlock — syncconf is stable and atomic.
//	Transfer stats are preserved across reloads.
//
// Fire-and-forget: returns immediately.
func (t *TunnelInterface) KernelRemovePeer(peerID string) {
	if !t.Enabled {
		return
	}
	if isAWGProtocol(t.Protocol) && isUserspaceMode() {
		// Userspace: syncconf is stable — use Reload() to preserve transfer stats.
		t.Reload()
		return
	}
	go func() {
		t.reloadMu.Lock()
		defer t.reloadMu.Unlock()
		if err := t.Restart(); err != nil {
			log.Printf("tunnel: KernelRemovePeer %s: restart failed: %v", peerID, err)
		}
	}()
}

// ── Config generation ─────────────────────────────────────────────────────────

// confDir is the directory where wg-quick / awg-quick look for configs.
// In the amneziavpn/amneziawg-go container image both binaries use this path.
const confDir = "/etc/amnezia/amneziawg"

// RegenerateConfig writes the wg-quick config to /etc/amnezia/amneziawg/<id>.conf (mode 0600).
func (t *TunnelInterface) RegenerateConfig() error {
	if err := os.MkdirAll(confDir, 0700); err != nil {
		return fmt.Errorf("mkdir %s: %w", confDir, err)
	}
	config := t.generateWgConfig()
	path := fmt.Sprintf("%s/%s.conf", confDir, t.ID)
	if err := os.WriteFile(path, []byte(config), 0600); err != nil {
		return fmt.Errorf("write config %s: %w", path, err)
	}
	log.Printf("tunnel: config regenerated: %s", path)
	return nil
}

// generateWgConfig builds the full wg-quick config string including PostUp/PostDown.
//
// FIX-1 rules for PostUp/PostDown:
//   - Use iptables-nft (Ubuntu 22.04 nftables backend, not plain iptables)
//   - Use -A FORWARD (append), never -I (insert) — keeps FIREWALL_FORWARD chain first
//   - Both -i and -o directions — traffic flows both ways
//   - MASQUERADE -s <subnet> -o $ISP — limits NAT to egress, not to wg* interfaces
//   - ISP interface resolved dynamically via `ip -4 route show default | awk 'NR==1{print $5}'`
func (t *TunnelInterface) generateWgConfig() string {
	var sb strings.Builder

	sb.WriteString("[Interface]\n")
	sb.WriteString(fmt.Sprintf("# %s\n", t.Name))
	sb.WriteString(fmt.Sprintf("PrivateKey = %s\n", t.PrivateKey))
	sb.WriteString(fmt.Sprintf("ListenPort = %d\n", t.ListenPort))

	if t.DisableRoutes {
		sb.WriteString("Table = off\n")
	}

	if t.MTU > 0 {
		sb.WriteString(fmt.Sprintf("MTU = %d\n", t.MTU))
	}

	if t.Address != "" {
		sb.WriteString(fmt.Sprintf("Address = %s\n", t.Address))

		subnet := cidrToSubnet(t.Address)
		// Dynamic ISP interface: name varies per host (eth0, ens3, ens18, ...).
		getISP := `ISP=$(ip -4 route show default | awk 'NR==1{print $5}')`
		// ip link set txqueuelen 500: reduces bufferbloat on WireGuard egress.
		// Default txqueuelen=1000 holds ~11ms at 1 Gbps; 500 → ~5.7ms.
		// Effective with BBR congestion control (set by tcp_tune.sh) which paces
		// traffic and rarely fills the queue — no throughput impact at 1 Gbps.
		//
		// Lifecycle note: txqueuelen is set at interface creation (PostUp = wg-quick up).
		// doReload() uses syncconf which does NOT tear down the interface, so the value
		// from Start() survives peer changes. Only a full Stop()+Start() resets it,
		// which re-executes PostUp and reapplies the setting.
		//
		// FIX-1 / plan auto-nat-rules-ui:
		//   FORWARD rules always apply (both -i and -o directions) for any interface with Address.
		//   MASQUERADE is added only when:
		//     - DisableRoutes=false (client interface, not S2S interconnect), AND
		//     - NatDisabled=false (user has not explicitly opted out of auto-NAT).
		//   S2S interconnect interfaces (DisableRoutes=true) must NOT get MASQUERADE —
		//   they route traffic between WireGuard networks without NATting.
		withNAT := !t.DisableRoutes && !t.NatDisabled
		var postUpNAT, postDownNAT string
		if withNAT {
			// Idempotency: -C check before -A prevents duplicate MASQUERADE rules on interface restart.
			// Without this, each awg-quick up appends a new rule regardless of existing ones.
			postUpNAT = fmt.Sprintf(
				"; iptables-nft -t nat -C POSTROUTING -s %s -o $ISP -j MASQUERADE 2>/dev/null || iptables-nft -t nat -A POSTROUTING -s %s -o $ISP -j MASQUERADE",
				subnet, subnet,
			)
			postDownNAT = fmt.Sprintf("; iptables-nft -t nat -D POSTROUTING -s %s -o $ISP -j MASQUERADE 2>/dev/null || true", subnet)
		}
		// MSS clamping — only for client interfaces (DisableRoutes=false).
		// Applied in both directions (-i and -o) to clamp MSS in SYN/RST packets.
		var postUpMSS, postDownMSS string
		if !t.DisableRoutes && t.MSS != 0 {
			var mssArg string
			if t.MSS == -1 {
				mssArg = "--clamp-mss-to-pmtu"
			} else {
				mssArg = fmt.Sprintf("--set-mss %d", t.MSS)
			}
			tcpFlags := "-p tcp --tcp-flags SYN,RST SYN -j TCPMSS"
			postUpMSS = fmt.Sprintf(
				"; iptables-nft -t mangle -A FORWARD -i %s %s %s; iptables-nft -t mangle -A FORWARD -o %s %s %s",
				t.ID, tcpFlags, mssArg, t.ID, tcpFlags, mssArg,
			)
			postDownMSS = fmt.Sprintf(
				"; iptables-nft -t mangle -D FORWARD -i %s %s %s 2>/dev/null || true; iptables-nft -t mangle -D FORWARD -o %s %s %s 2>/dev/null || true",
				t.ID, tcpFlags, mssArg, t.ID, tcpFlags, mssArg,
			)
		}
		postUp := fmt.Sprintf(
			"PostUp = %s; ip link set %s txqueuelen 500; iptables-nft -C FORWARD -i %s -j ACCEPT 2>/dev/null || iptables-nft -A FORWARD -i %s -j ACCEPT; iptables-nft -C FORWARD -o %s -j ACCEPT 2>/dev/null || iptables-nft -A FORWARD -o %s -j ACCEPT%s%s\n",
			getISP, t.ID, t.ID, t.ID, t.ID, t.ID, postUpNAT, postUpMSS,
		)
		postDown := fmt.Sprintf(
			"PostDown = %s; iptables-nft -D FORWARD -i %s -j ACCEPT 2>/dev/null || true; iptables-nft -D FORWARD -o %s -j ACCEPT 2>/dev/null || true%s%s\n",
			getISP, t.ID, t.ID, postDownNAT, postDownMSS,
		)
		sb.WriteString(postUp)
		sb.WriteString(postDown)
	}

	// AmneziaWG 2.0 obfuscation parameters.
	if isAWGProtocol(t.Protocol) && t.AWG2 != nil {
		a := t.AWG2
		sb.WriteString("\n# AmneziaWG Parameters\n")
		sb.WriteString(fmt.Sprintf("Jc = %d\n", a.Jc))
		sb.WriteString(fmt.Sprintf("Jmin = %d\n", a.Jmin))
		sb.WriteString(fmt.Sprintf("Jmax = %d\n", a.Jmax))
		sb.WriteString(fmt.Sprintf("S1 = %d\n", a.S1))
		sb.WriteString(fmt.Sprintf("S2 = %d\n", a.S2))
		sb.WriteString(fmt.Sprintf("S3 = %d\n", a.S3))
		sb.WriteString(fmt.Sprintf("S4 = %d\n", a.S4))
		sb.WriteString(fmt.Sprintf("H1 = %s\n", a.H1))
		sb.WriteString(fmt.Sprintf("H2 = %s\n", a.H2))
		sb.WriteString(fmt.Sprintf("H3 = %s\n", a.H3))
		sb.WriteString(fmt.Sprintf("H4 = %s\n", a.H4))
		if a.I1 != "" {
			sb.WriteString(fmt.Sprintf("I1 = %s\n", a.I1))
		}
		if a.I2 != "" {
			sb.WriteString(fmt.Sprintf("I2 = %s\n", a.I2))
		}
		if a.I3 != "" {
			sb.WriteString(fmt.Sprintf("I3 = %s\n", a.I3))
		}
		if a.I4 != "" {
			sb.WriteString(fmt.Sprintf("I4 = %s\n", a.I4))
		}
		if a.I5 != "" {
			sb.WriteString(fmt.Sprintf("I5 = %s\n", a.I5))
		}
		writeAWG3Settings(&sb, t.Protocol, a)
	}

	// [Peer] sections. Disabled peers return "" from ToWgConfig().
	t.peersMu.RLock()
	for _, p := range t.peers {
		sb.WriteString(p.ToWgConfig())
	}
	t.peersMu.RUnlock()

	return sb.String()
}

// generateSyncConfig builds the stripped config suitable for `wg/awg syncconf`.
// Excludes wg-quick-specific directives (Address, Table, PostUp, PostDown, DNS, MTU).
// Used as a fallback when bash process substitution is unavailable.
func (t *TunnelInterface) generateSyncConfig() string {
	var sb strings.Builder

	sb.WriteString("[Interface]\n")
	sb.WriteString(fmt.Sprintf("PrivateKey = %s\n", t.PrivateKey))
	sb.WriteString(fmt.Sprintf("ListenPort = %d\n", t.ListenPort))

	if isAWGProtocol(t.Protocol) && t.AWG2 != nil {
		a := t.AWG2
		sb.WriteString(fmt.Sprintf("Jc = %d\n", a.Jc))
		sb.WriteString(fmt.Sprintf("Jmin = %d\n", a.Jmin))
		sb.WriteString(fmt.Sprintf("Jmax = %d\n", a.Jmax))
		sb.WriteString(fmt.Sprintf("S1 = %d\n", a.S1))
		sb.WriteString(fmt.Sprintf("S2 = %d\n", a.S2))
		sb.WriteString(fmt.Sprintf("S3 = %d\n", a.S3))
		sb.WriteString(fmt.Sprintf("S4 = %d\n", a.S4))
		sb.WriteString(fmt.Sprintf("H1 = %s\n", a.H1))
		sb.WriteString(fmt.Sprintf("H2 = %s\n", a.H2))
		sb.WriteString(fmt.Sprintf("H3 = %s\n", a.H3))
		sb.WriteString(fmt.Sprintf("H4 = %s\n", a.H4))
		if a.I1 != "" {
			sb.WriteString("I1 = " + a.I1 + "\n")
		}
		if a.I2 != "" {
			sb.WriteString("I2 = " + a.I2 + "\n")
		}
		if a.I3 != "" {
			sb.WriteString("I3 = " + a.I3 + "\n")
		}
		if a.I4 != "" {
			sb.WriteString("I4 = " + a.I4 + "\n")
		}
		if a.I5 != "" {
			sb.WriteString("I5 = " + a.I5 + "\n")
		}
		writeAWG3Settings(&sb, t.Protocol, a)
	}

	t.peersMu.RLock()
	for _, p := range t.peers {
		sb.WriteString(p.ToWgConfig())
	}
	t.peersMu.RUnlock()

	return sb.String()
}

// ── Status polling ────────────────────────────────────────────────────────────

// GetStatus fetches live transfer stats and handshake timestamps from
// `wg/awg show <id> dump` and updates the runtime fields on in-memory peers.
// NOT persisted. Called every ~1 s by InterfaceManager (FIX-10: 5 s timeout).
func (t *TunnelInterface) GetStatus() {
	if !t.Enabled {
		return
	}
	startedAt := time.Now()

	// Status collection is periodic, so successful commands stay out of the log.
	// Errors are still logged below via log.Printf.
	out, err := util.ExecSilentFast(fmt.Sprintf("%s show %s dump", t.syncBin(), t.ID))
	if err != nil {
		metrics.RecordStatusCommand(t.ID, time.Since(startedAt), false)
		log.Printf("tunnel: getStatus %s: %v", t.ID, err)
		return
	}
	metrics.RecordStatusCommand(t.ID, time.Since(startedAt), true)

	lines := strings.Split(strings.TrimSpace(out), "\n")
	if len(lines) <= 1 {
		return // no peers or empty output
	}

	// Tab-separated columns per peer line:
	//   0: public_key   1: preshared_key   2: endpoint   3: allowed_ips
	//   4: latest_handshake (unix ts)   5: transfer_rx   6: transfer_tx   7: persistent_keepalive
	t.peersMu.RLock()
	defer t.peersMu.RUnlock()

	t.trafficMu.Lock()
	defer t.trafficMu.Unlock()

	for _, line := range lines[1:] { // lines[0] is the interface row
		fields := strings.Split(line, "\t")
		if len(fields) < 7 {
			continue
		}
		pubKey := fields[0]
		endpoint := fields[2]
		tsStr := fields[4]
		rxStr := fields[5]
		txStr := fields[6]

		for _, p := range t.peers {
			if p.PublicKey != pubKey {
				continue
			}
			if ts, e := strconv.ParseInt(tsStr, 10, 64); e == nil && ts > 0 {
				s := time.Unix(ts, 0).UTC().Format(time.RFC3339)
				if p.LatestHandshakeAt == nil || *p.LatestHandshakeAt != s {
					p.LatestHandshakeAt = &s
					if err := peer.SaveHandshake(p.ID, s); err != nil {
						log.Printf("tunnel: save handshake %s: %v", p.ID, err)
					}
				}
			}
			// ts == 0 means peer has not handshaked since wg started — keep the
			// persisted value so "last seen" survives container restarts.

			var newRx, newTx int64
			if rx, e := strconv.ParseInt(rxStr, 10, 64); e == nil {
				p.TransferRx = rx
				newRx = rx
			}
			if tx, e := strconv.ParseInt(txStr, 10, 64); e == nil {
				p.TransferTx = tx
				newTx = tx
			}

			// Accumulate traffic delta into lifetime totals.
			// delta = max(0, newKernel - lastSeen): negative means counter reset
			// (wg-quick down was called), treat as 0 to avoid subtracting from total.
			if st := t.trafficState[p.ID]; st != nil {
				dRx := newRx - st.lastSeenRx
				if dRx < 0 {
					dRx = 0
				}
				dTx := newTx - st.lastSeenTx
				if dTx < 0 {
					dTx = 0
				}
				if dRx > 0 || dTx > 0 {
					st.totalRx += dRx
					st.totalTx += dTx
					st.dirty = true
				}
				st.lastSeenRx = newRx
				st.lastSeenTx = newTx
				p.TotalRx = st.totalRx
				p.TotalTx = st.totalTx
			} else {
				// trafficState not yet initialised for this peer (race during AddPeer).
				// Copy kernel counter as initial baseline — no delta yet.
				if t.trafficState == nil {
					t.trafficState = make(map[string]*peerTrafficState)
				}
				t.trafficState[p.ID] = &peerTrafficState{
					lastSeenRx: newRx,
					lastSeenTx: newTx,
				}
			}

			if endpoint != "" && endpoint != "(none)" {
				p.RuntimeEndpoint = endpoint
			}
			break
		}
	}
}

// FlushTrafficTotals persists dirty traffic totals to SQLite.
// Called before wg-quick down (in Stop) and every 60 s by the polling goroutine.
// No-op if trafficState is nil or nothing is dirty.
func (t *TunnelInterface) FlushTrafficTotals() {
	t.trafficMu.Lock()
	defer t.trafficMu.Unlock()

	for peerID, st := range t.trafficState {
		if !st.dirty {
			continue
		}
		if err := peer.SaveTrafficTotals(peerID, st.totalRx, st.totalTx); err != nil {
			log.Printf("tunnel: flush traffic %s/%s: %v", t.ID, peerID, err)
			continue
		}
		st.dirty = false
	}
}

// ── IP allocation ─────────────────────────────────────────────────────────────

// AutoAllocateIP returns the next available IP in the interface subnet as "<ip>/32".
// Skips the interface's own IP and all IPs already allocated to peers.
func (t *TunnelInterface) AutoAllocateIP() (string, error) {
	if t.Address == "" {
		return "", fmt.Errorf("interface %s has no address configured", t.ID)
	}

	_, ipNet, err := net.ParseCIDR(t.Address)
	if err != nil {
		return "", fmt.Errorf("parse interface address %q: %w", t.Address, err)
	}

	// Collect used IPs: interface's own IP.
	used := make(map[uint32]bool)
	ifaceIPStr := strings.SplitN(t.Address, "/", 2)[0]
	if ip4 := net.ParseIP(ifaceIPStr).To4(); ip4 != nil {
		used[binary.BigEndian.Uint32(ip4)] = true
	}

	// Add all peer first-IPs.
	t.peersMu.RLock()
	for _, p := range t.peers {
		if p.AllowedIPs == "" {
			continue
		}
		firstCIDR := strings.TrimSpace(strings.Split(p.AllowedIPs, ",")[0])
		ipStr := strings.SplitN(firstCIDR, "/", 2)[0]
		if ip4 := net.ParseIP(ipStr).To4(); ip4 != nil {
			used[binary.BigEndian.Uint32(ip4)] = true
		}
	}
	t.peersMu.RUnlock()

	// Scan from network+1 to broadcast-1.
	networkIP := ipNet.IP.To4()
	networkN := binary.BigEndian.Uint32(networkIP)
	ones, bits := ipNet.Mask.Size()
	hostBits := uint32(bits - ones)
	broadcastN := networkN | ((1 << hostBits) - 1)

	for i := networkN + 1; i < broadcastN; i++ {
		if !used[i] {
			ip := make(net.IP, 4)
			binary.BigEndian.PutUint32(ip, i)
			return ip.String() + "/32", nil
		}
	}

	return "", fmt.Errorf("no available IP addresses in subnet %s", ipNet)
}

// resolvedHost returns the effective public host for this interface.
// Priority: per-interface PublicHost → wgHostResolved (caller's pre-resolved global value).
// The caller must resolve the global host (via settings.GetWGHost) before calling this.
func (t *TunnelInterface) resolvedHost(wgHostResolved string) string {
	if t.PublicHost != "" {
		return t.PublicHost
	}
	return wgHostResolved
}

// ── Export helpers ────────────────────────────────────────────────────────────

// ExportInterfaceParams returns this interface's parameters for S2S interconnect.
// wgHost is the value of WG_HOST env var (public IP/hostname).
//
// PSK is included only if an interconnect peer with a preshared key exists —
// this enables the "step 2" side to share the PSK back with "step 1":
//
//	A exports (no PSK yet) → B imports → B generates PSK → B exports (PSK included) → A imports PSK
func (t *TunnelInterface) ExportInterfaceParams(wgHost string) InterfaceExport {
	host := t.resolvedHost(wgHost)
	endpoint := ""
	if host != "" {
		endpoint = fmt.Sprintf("%s:%d", host, t.ListenPort)
	}

	// Find PSK from the most recent interconnect peer.
	var psk string
	t.peersMu.RLock()
	for _, p := range t.peers {
		if p.PeerType == "interconnect" && p.PresharedKey != "" {
			psk = p.PresharedKey
			break
		}
	}
	t.peersMu.RUnlock()

	exp := InterfaceExport{
		Name:      t.Name,
		PublicKey: t.PublicKey,
		Endpoint:  endpoint,
		Address:   t.Address,
		Protocol:  t.Protocol,
	}
	// For transit/S2S interfaces (DisableRoutes=true) export AllowedIPs=0.0.0.0/0
	// so the importing side routes all traffic through this peer.
	// For point-to-point interfaces (DisableRoutes=false) omit AllowedIPs —
	// importPeerJSON will derive /32 from the address field instead.
	// Note: FIX-GO-11 ensures inp.Address is always written from body["address"]
	// independently of allowedIPs, so 0.0.0.0/0 no longer causes empty address.
	if t.DisableRoutes {
		exp.AllowedIPs = "0.0.0.0/0"
	}
	if psk != "" {
		exp.PresharedKey = psk
	}
	return exp
}

// ExportObfuscationParams returns a copy of this interface's AmneziaWG parameters.
func (t *TunnelInterface) ExportObfuscationParams() (*peer.AWG2Settings, error) {
	if !isAWGProtocol(t.Protocol) {
		return nil, fmt.Errorf("obfuscation params are only available for AmneziaWG interfaces")
	}
	if t.AWG2 == nil {
		return nil, fmt.Errorf("interface %s has no AWG2 params configured", t.ID)
	}
	cp := *t.AWG2 // return a copy — callers must not mutate our state
	return &cp, nil
}

// ── Internal helpers ──────────────────────────────────────────────────────────

// cidrToSubnet returns the network address from a CIDR string.
// e.g. "10.8.0.1/24" → "10.8.0.0/24"
func cidrToSubnet(cidr string) string {
	_, ipNet, err := net.ParseCIDR(cidr)
	if err != nil {
		return cidr
	}
	return ipNet.String()
}

// boolInt converts bool to 0/1 for SQLite integer columns.
func boolInt(b bool) int {
	if b {
		return 1
	}
	return 0
}

// scanInterface reads one interface row from SQLite into a TunnelInterface.
func scanInterface(id string) (*TunnelInterface, error) {
	row := db.DB().QueryRow(`
		SELECT id, name, address, listen_port, protocol, enabled, disable_routes, nat_disabled,
		       dns, public_host, mtu, mss, uplink, private_key, public_key,
		       jc, jmin, jmax, s1, s2, s3, s4, h1, h2, h3, h4,
		       i1, i2, i3, i4, i5, header_protection_key, content_padding_addition,
		       rekey_after_time, rekey_timeout, reject_after_time, keepalive_timeout,
		       max_handshake_attempts, random_trailers, disable_cookies, created_at
		FROM interfaces WHERE id = ?`, id)

	t := &TunnelInterface{}
	var (
		enabled, disableRoutes, natDisabled, uplink   int
		jc, jmin, jmax                                sql.NullInt64
		s1, s2, s3, s4                                sql.NullInt64
		h1, h2, h3, h4                                sql.NullString
		i1, i2, i3, i4, i5                            sql.NullString
		headerProtectionKey, contentPaddingAddition   sql.NullString
		rekeyAfterTime, rekeyTimeout, rejectAfterTime sql.NullString
		keepaliveTimeout, maxHandshakeAttempts        sql.NullString
		randomTrailers, disableCookies                sql.NullInt64
	)

	err := row.Scan(
		&t.ID, &t.Name, &t.Address, &t.ListenPort, &t.Protocol,
		&enabled, &disableRoutes, &natDisabled,
		&t.DNS, &t.PublicHost, &t.MTU, &t.MSS, &uplink, &t.PrivateKey, &t.PublicKey,
		&jc, &jmin, &jmax,
		&s1, &s2, &s3, &s4,
		&h1, &h2, &h3, &h4,
		&i1, &i2, &i3, &i4, &i5,
		&headerProtectionKey, &contentPaddingAddition, &rekeyAfterTime, &rekeyTimeout,
		&rejectAfterTime, &keepaliveTimeout, &maxHandshakeAttempts,
		&randomTrailers, &disableCookies,
		&t.CreatedAt,
	)
	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("interface %q not found", id)
	}
	if err != nil {
		return nil, err
	}

	t.Enabled = enabled == 1
	t.DisableRoutes = disableRoutes == 1
	t.NatDisabled = natDisabled == 1
	t.Uplink = uplink == 1
	t.peers = make(map[string]*peer.Peer)

	// AWG2 params are stored as nullable columns; reconstruct only if Jc is present.
	if jc.Valid {
		t.AWG2 = &peer.AWG2Settings{
			Jc: int(jc.Int64), Jmin: int(jmin.Int64), Jmax: int(jmax.Int64),
			S1: int(s1.Int64), S2: int(s2.Int64), S3: int(s3.Int64), S4: int(s4.Int64),
			H1: h1.String, H2: h2.String, H3: h3.String, H4: h4.String,
			I1: i1.String, I2: i2.String, I3: i3.String, I4: i4.String, I5: i5.String,
			HeaderProtectionKey:    headerProtectionKey.String,
			ContentPaddingAddition: contentPaddingAddition.String,
			RekeyAfterTime:         rekeyAfterTime.String, RekeyTimeout: rekeyTimeout.String,
			RejectAfterTime: rejectAfterTime.String, KeepaliveTimeout: keepaliveTimeout.String,
			MaxHandshakeAttempts: maxHandshakeAttempts.String,
		}
		if randomTrailers.Valid {
			v := randomTrailers.Int64 == 1
			t.AWG2.RandomTrailers = &v
		}
		if disableCookies.Valid {
			v := disableCookies.Int64 == 1
			t.AWG2.DisableCookies = &v
		}
	}

	return t, nil
}

func isAWGProtocol(protocol string) bool {
	return protocol == "amneziawg-2.0" || protocol == "amneziawg-3.1"
}

func writeAWG3Settings(sb *strings.Builder, protocol string, a *peer.AWGSettings) {
	if protocol != "amneziawg-3.1" {
		return
	}
	fmt.Fprintf(sb, "HeaderProtectionKey = %s\n", a.HeaderProtectionKey)
	fmt.Fprintf(sb, "ContentPaddingAddition = %s\n", a.ContentPaddingAddition)
	fmt.Fprintf(sb, "RekeyAfterTime = %s\n", a.RekeyAfterTime)
	fmt.Fprintf(sb, "RekeyTimeout = %s\n", a.RekeyTimeout)
	fmt.Fprintf(sb, "RejectAfterTime = %s\n", a.RejectAfterTime)
	fmt.Fprintf(sb, "KeepaliveTimeout = %s\n", a.KeepaliveTimeout)
	fmt.Fprintf(sb, "MaxHandshakeAttempts = %s\n", a.MaxHandshakeAttempts)
	if a.RandomTrailers != nil {
		fmt.Fprintf(sb, "RandomTrailers = %s\n", peer.FormatAWGBool(*a.RandomTrailers))
	}
	if a.DisableCookies != nil {
		fmt.Fprintf(sb, "DisableCookies = %s\n", peer.FormatAWGBool(*a.DisableCookies))
	}
}
