#!/usr/bin/env bash
# =============================================================================
# Cascade — Full deployment script
# Ubuntu 22.04 / 24.04 and Debian 13, run as root
# Usage:  bash deploy/setup.sh
#         bash deploy/setup.sh --yes              # non-interactive (reads all from .env)
#         bash deploy/setup.sh --staging          # use Let's Encrypt staging CA (testing)
#         bash deploy/setup.sh --yes --staging    # non-interactive + staging
#         bash deploy/setup.sh --yes --prefer-ipv6  # auto-detect IPv6 address instead of IPv4
# =============================================================================
set -euo pipefail

# ── Paths ────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNTIME_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$RUNTIME_DIR/.env"
CADDY_DIR="$SCRIPT_DIR/caddy"
CERT_DIR="/etc/ssl/cascade"
REBOOT_FLAG="/var/lib/.cascade-needs-reboot"
LOG_FILE="/var/log/cascade-setup.log"
DEPENDENCY_HELPERS="$SCRIPT_DIR/lib/install-dependencies.sh"

[[ -f "$DEPENDENCY_HELPERS" ]] || { echo "Missing dependency helpers: $DEPENDENCY_HELPERS" >&2; exit 1; }
# shellcheck source=deploy/lib/install-dependencies.sh
source "$DEPENDENCY_HELPERS"

# ── Logging to file ──────────────────────────────────────────────────────────
mkdir -p "$(dirname "$LOG_FILE")"
exec > >(tee -a "$LOG_FILE") 2>&1
echo "=== cascade setup started at $(date -u '+%Y-%m-%dT%H:%M:%SZ') ==="

# ── Colors ───────────────────────────────────────────────────────────────────
G='\033[0;32m'; Y='\033[1;33m'; R='\033[0;31m'; B='\033[0;34m'; N='\033[0m'

# ── Docker Compose command (v2 plugin or v1 standalone) ───────────────────────
# Resolved after Docker is confirmed installed (Step 3).
# Use COMPOSE_CMD everywhere instead of hardcoded "docker compose".
resolve_compose() {
  if docker compose version &>/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
  elif command -v docker-compose &>/dev/null; then
    COMPOSE_CMD="docker-compose"
  else
    fail "docker compose not found. Install docker-compose-plugin: apt install docker-compose-plugin"
  fi
  ok "Compose: $COMPOSE_CMD"
}
COMPOSE_CMD="docker compose"  # default, overridden by resolve_compose after Step 3

compose_files() {
  local compose_file="$1"
  COMPOSE_ARGS=(-f "$compose_file")
  if [[ -f "$RUNTIME_DIR/docker-compose.override.yml" ]]; then
    COMPOSE_ARGS+=(-f "$RUNTIME_DIR/docker-compose.override.yml")
  fi
}

ok()   { echo -e "${G}  [✓]${N} $*"; }
info() { echo -e "${B}  [→]${N} $*"; }
warn() { echo -e "${Y}  [!]${N} $*"; }
fail() { echo -e "${R}  [✗]${N} $*"; exit 1; }

# ── Parse args ───────────────────────────────────────────────────────────────
YES=0
PREFER_IPV6=0
ACME_STAGING=${ACME_STAGING:-0}   # overridable from .env; --staging flag sets to 1
for arg in "$@"; do
  [[ "$arg" == "--yes"        ]] && YES=1
  [[ "$arg" == "--staging"    ]] && ACME_STAGING=1
  [[ "$arg" == "--prefer-ipv6" ]] && PREFER_IPV6=1
done

# ── Load .env ────────────────────────────────────────────────────────────────
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

CADDY_IMAGE="${CADDY_IMAGE:-caddy:alpine}"
export CADDY_IMAGE

# ── Helpers ──────────────────────────────────────────────────────────────────
ask() {
  # ask VAR "Prompt" [default]
  local var="$1" prompt="$2" default="${3:-}"
  local current="${!var:-}"
  [[ -n "$current" ]] && { ok "$prompt: (loaded from .env: $current)"; return; }
  if [[ $YES -eq 1 ]]; then
    [[ -n "$default" ]] && printf -v "$var" '%s' "$default" && return
    fail "$prompt is required — set in $ENV_FILE"
  fi
  local hint=""; [[ -n "$default" ]] && hint=" [$default]"
  read -rp "  $prompt$hint: " val
  printf -v "$var" '%s' "${val:-$default}"
}

save_env() {
  # Rewrite .env with current values (no plaintext passwords).
  # WG_QUICK_USERSPACE_IMPLEMENTATION is written directly so docker-compose
  # env_file can inject it into the container without host-side interpolation.
  local userspace_val=""
  [[ "${AWG_USERSPACE_IMPL:-}" == "amneziawg-go" ]] && userspace_val="amneziawg-go"
  cat > "$ENV_FILE" << EOF
# Cascade runtime config — generated by setup.sh
# All values here are injected into the container via env_file.
# Edit only the Cascade image tag in docker-compose.yml when updating.
CADDY_IMAGE=${CADDY_IMAGE}
WG_HOST=${WG_HOST:-}
ADMIN_PATH=${ADMIN_PATH:-}
ACME_EMAIL=${ACME_EMAIL:-}
ACME_STAGING=${ACME_STAGING:-0}
CASCADE_PORT=${CASCADE_PORT:-8888}
PORT=${CASCADE_PORT:-8888}
BIND_ADDR=${BIND_ADDR:-127.0.0.1}
AWG_USERSPACE_IMPL=${AWG_USERSPACE_IMPL:-}
WG_QUICK_USERSPACE_IMPLEMENTATION=${userspace_val}
NETWORK_MODE=${NETWORK_MODE:-host}
BRIDGE_PORT_RANGE=${BRIDGE_PORT_RANGE:-}
EOF
  chmod 600 "$ENV_FILE"
}

# generate_bridge_compose — create docker-compose.bridge.yml from template
# Substitutes __WG_PORT_RANGE__ and __CASCADE_PORT__ placeholders.
generate_bridge_compose() {
  local port_range="$1" mgmt_port="$2"
  local tmpl="$RUNTIME_DIR/deploy/docker-compose.bridge.yml.example"
  # Output to repo root — same directory as docker-compose.yml and docker-compose.isolated.yml.
  # This ensures that env_file: .env resolves correctly (relative to runtime root),
  # matching the pattern used by docker-compose.yml.
  local out="$RUNTIME_DIR/docker-compose.bridge.yml"
  [[ ! -f "$tmpl" ]] && fail "Template not found: $tmpl"
  sed -e "s|__WG_PORT_RANGE__|${port_range}|g" \
      -e "s|__CASCADE_PORT__|${mgmt_port}|g" \
      "$tmpl" > "$out"
  ok "Generated $out (range: $port_range, port: $mgmt_port)"
}

is_ip() { [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; }

detect_ip() {
  local ip
  if [[ "${PREFER_IPV6:-0}" == "1" ]]; then
    # IPv6 preferred (--prefer-ipv6 flag): try IPv6 first, fall back to IPv4.
    ip=$(curl -6 -s --max-time 5 https://ifconfig.me 2>/dev/null)    && [[ -n "$ip" ]] && echo "$ip" && return
    ip=$(curl -6 -s --max-time 5 https://api6.ipify.org 2>/dev/null) && [[ -n "$ip" ]] && echo "$ip" && return
  fi
  # Default: prefer IPv4 (-4 forces IPv4 transport).
  # On dual-stack hosts curl without -4 may pick IPv6 → admin URL gets IPv6 literal
  # which breaks access for users without IPv6 connectivity.
  ip=$(curl -4 -s --max-time 5 https://ifconfig.me 2>/dev/null)    && [[ -n "$ip" ]] && echo "$ip" && return
  ip=$(curl -4 -s --max-time 5 https://api4.ipify.org 2>/dev/null) && [[ -n "$ip" ]] && echo "$ip" && return
  ip=$(ip route get 8.8.8.8 2>/dev/null | awk '/src/{print $7}')   && [[ -n "$ip" ]] && echo "$ip" && return
  echo ""
}

# ── Must run as root ──────────────────────────────────────────────────────────
[[ $EUID -ne 0 ]] && fail "Run as root (sudo bash deploy/setup.sh)"

# ── Banner ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${B}╔══════════════════════════════════════╗${N}"
echo -e "${B}║       Cascade — Deploy Setup         ║${N}"
echo -e "${B}╚══════════════════════════════════════╝${N}"
echo ""

# ── Detect OS ─────────────────────────────────────────────────────────────────
OS_ID=$(grep '^ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
OS_VER=$(grep '^VERSION_ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
OS_CODENAME=$(grep '^VERSION_CODENAME=' /etc/os-release | cut -d= -f2 | tr -d '"')
KERNEL_MAJOR=$(uname -r | cut -d. -f1)

cascade_validate_supported_os "$OS_ID" "$OS_VER" || fail "This operating system is not supported by the automated installer"
[[ -n "$OS_CODENAME" ]] || fail "VERSION_CODENAME is missing from /etc/os-release"
info "OS: $OS_ID $OS_VER ($OS_CODENAME)  |  Kernel: $(uname -r)"

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 0 — Swap (1 GB)
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 0: Swap${N}"

SWAPFILE=/swapfile
if swapon --show | grep -q "$SWAPFILE"; then
  ok "Swap already active ($SWAPFILE)"
elif [[ -f "$SWAPFILE" ]]; then
  info "Swap file exists but not active — activating..."
  chmod 600 "$SWAPFILE"
  mkswap "$SWAPFILE" > /dev/null
  swapon "$SWAPFILE"
  ok "Swap activated ($(du -h "$SWAPFILE" | cut -f1))"
else
  info "Creating 1 GB swap at $SWAPFILE..."
  fallocate -l 1G "$SWAPFILE" 2>/dev/null || dd if=/dev/zero of="$SWAPFILE" bs=1M count=1024 status=none
  chmod 600 "$SWAPFILE"
  mkswap "$SWAPFILE" > /dev/null
  swapon "$SWAPFILE"
  ok "Swap created and activated (1 GB)"
fi

# Persist across reboots
if ! grep -q "$SWAPFILE" /etc/fstab; then
  echo "$SWAPFILE none swap sw 0 0" >> /etc/fstab
  ok "Added $SWAPFILE to /etc/fstab"
fi

# Tune swappiness: use swap only under real memory pressure
sysctl -w vm.swappiness=10 > /dev/null
if ! grep -q 'vm.swappiness' /etc/sysctl.d/99-cascade.conf 2>/dev/null; then
  echo 'vm.swappiness=10' >> /etc/sysctl.d/99-cascade.conf
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 1 — Kernel upgrade (Ubuntu 22.04 only)
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 1: Kernel${N}"

if [[ "$OS_VER" == "22.04" && "$KERNEL_MAJOR" -lt 6 ]]; then
  if [[ -f "$REBOOT_FLAG" ]]; then
    fail "Reboot flag found but kernel is still $KERNEL_MAJOR.x — did you reboot? Remove $REBOOT_FLAG and rerun after rebooting."
  fi
  info "Ubuntu 22.04 with kernel $KERNEL_MAJOR.x — upgrading to HWE 6.x..."
  apt-get update -qq
  apt-get install -y linux-generic-hwe-22.04
  touch "$REBOOT_FLAG"
  echo ""
  echo -e "${Y}  ┌─────────────────────────────────────────────────┐${N}"
  echo -e "${Y}  │  Kernel upgraded. REBOOT REQUIRED.              │${N}"
  echo -e "${Y}  │  After reboot, run:  bash deploy/setup.sh       │${N}"
  echo -e "${Y}  └─────────────────────────────────────────────────┘${N}"
  echo ""
  exit 0
else
  [[ -f "$REBOOT_FLAG" ]] && rm -f "$REBOOT_FLAG"
  ok "Kernel $(uname -r) — OK"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 2 — AmneziaWG run mode (userspace vs kernel)
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 2: AmneziaWG run mode${N}"

# ── Helpers for applying run mode ────────────────────────────────────────────
apply_userspace_mode() {
  # Unload kernel module if loaded — amneziawg-go defers to kernel when present
  if lsmod | grep -q amneziawg; then
    info "Unloading amneziawg kernel module (userspace mode selected)..."
    modprobe -r amneziawg 2>/dev/null || warn "Could not unload amneziawg — reboot required"
  fi
  echo "blacklist amneziawg" > /etc/modprobe.d/amneziawg-blacklist.conf
  rm -f /etc/modules-load.d/amneziawg.conf
  ok "Kernel module unloaded and blacklisted"
}

apply_kernel_mode() {
  # DKMS needs headers matching the RUNNING kernel to build amneziawg.ko —
  # without this, the dkms build step silently skips ("kernel headers for
  # this kernel do not seem to be installed") and modprobe fails afterward.
  # Step 1 above only installs headers as a side effect of the HWE upgrade
  # on Ubuntu 22.04 kernels <6; on 24.04 (or any host already on 6.x) that
  # step is skipped entirely, so headers are otherwise never installed.
  #
  # Check the actual build symlink DKMS needs rather than dpkg's package
  # state — a headers package left in "removed, config remains" (rc) or a
  # half-installed state would still make `dpkg -l` exit 0, silently
  # skipping this fix in exactly the case it exists to catch.
  if [[ ! -e "/lib/modules/$(uname -r)/build" ]]; then
    info "Installing kernel headers for $(uname -r) (required for DKMS)..."
    # Try with the current apt cache first; only pay for `apt-get update` if
    # that fails (e.g. stale lists on a freshly-provisioned VPS).
    if ! apt-get install -y "linux-headers-$(uname -r)" 2>/dev/null; then
      apt-get update -qq
      if ! apt-get install -y "linux-headers-$(uname -r)"; then
        warn "Exact-version headers unavailable — falling back to linux-headers-generic"
        apt-get install -y linux-headers-generic || \
          fail "Could not install kernel headers for $(uname -r) — DKMS build for amneziawg would fail. Install headers manually and re-run setup.sh."
      fi
    fi
  fi
  [[ -e "/lib/modules/$(uname -r)/build" ]] || \
    fail "Could not find kernel headers for $(uname -r) — DKMS build for amneziawg would fail. Install matching headers and re-run setup.sh."

  # Remove blacklist (if switching from userspace)
  rm -f /etc/modprobe.d/amneziawg-blacklist.conf
  if ! dpkg-query -W -f='${db:Status-Status}' amneziawg 2>/dev/null | grep -qx installed || \
     ! dpkg-query -W -f='${db:Status-Status}' amneziawg-dkms 2>/dev/null | grep -qx installed; then
    info "Installing AmneziaWG kernel module (ppa:amnezia/ppa)..."
    add-apt-repository -y ppa:amnezia/ppa > /dev/null 2>&1
    apt-get update -qq
    apt-get install -y amneziawg amneziawg-dkms
  else
    info "AmneziaWG and DKMS packages are installed"
  fi

  module_loaded() {
    lsmod | grep -q '^amneziawg[[:space:]]' 2>/dev/null
  }
  module_version() {
    if [[ -r /sys/module/amneziawg/version ]]; then
      tr -d '[:space:]' < /sys/module/amneziawg/version
    else
      modinfo -F version amneziawg 2>/dev/null | head -n 1 | tr -d '[:space:]'
    fi
  }
  installed_module_version() {
    modinfo -F version amneziawg 2>/dev/null | head -n 1 | tr -d '[:space:]'
  }
  version_line() {
    sed -nE 's/.*v?([0-9]+\.[0-9]+).*/\1/p' | head -n 1
  }

  installed_version="$(installed_module_version | version_line)"
  [[ -n "$installed_version" ]] || \
    fail "Cannot determine installed amneziawg module version; verify /lib/modules and kmod"

  loaded_version=""
  if module_loaded; then
    loaded_version="$(module_version | version_line)"
  fi

  if module_loaded && [[ -n "$loaded_version" && "$loaded_version" == "$installed_version" ]]; then
    echo "amneziawg" > /etc/modules-load.d/amneziawg.conf
    ok "amneziawg already loaded and synchronized (${installed_version})"
    return
  fi

  if module_loaded; then
    info "Synchronizing loaded module (${loaded_version:-unknown} → ${installed_version})..."
    modprobe -r amneziawg || fail "Could not unload the old amneziawg module; Cascade was not restarted"
  else
    info "Loading amneziawg kernel module (${installed_version})..."
  fi

  modprobe amneziawg || fail "Could not load amneziawg ${installed_version}; Cascade was not restarted"
  echo "amneziawg" > /etc/modules-load.d/amneziawg.conf
  loaded_version="$(module_version | version_line)"
  if ! module_loaded || [[ -z "$loaded_version" || "$loaded_version" != "$installed_version" ]]; then
    fail "Loaded amneziawg module version ${loaded_version:-unknown} does not match installed ${installed_version}; Cascade was not restarted"
  fi
  ok "amneziawg synchronized and loaded (${loaded_version})"
}

# Load saved mode from .env if present, otherwise ask
if [[ "${AWG_USERSPACE_IMPL:-unset}" != "unset" ]]; then
  if [[ "$AWG_USERSPACE_IMPL" == "amneziawg-go" ]]; then
    echo -e "  Current mode: ${G}Userspace (amneziawg-go)${N}"
  else
    echo -e "  Current mode: ${Y}Kernel module${N}"
  fi
  echo ""
  if [[ $YES -eq 1 ]]; then
    CHANGE_MODE="n"
  else
    read -rp "  Change run mode? [y/N]: " CHANGE_MODE
    CHANGE_MODE="${CHANGE_MODE:-n}"
  fi

  if [[ "${CHANGE_MODE,,}" == "y" ]]; then
    # Re-ask the choice
    AWG_USERSPACE_IMPL=""
  fi
fi

if [[ "${AWG_USERSPACE_IMPL:-unset}" != "unset" ]]; then
  # Mode confirmed, apply it
  if [[ "$AWG_USERSPACE_IMPL" == "amneziawg-go" ]]; then
    ok "Run mode: Userspace"
    apply_userspace_mode
  else
    ok "Run mode: Kernel module"
    apply_kernel_mode
  fi
else
  echo ""
  echo -e "  ${B}Choose AmneziaWG run mode:${N}"
  echo -e "  ${G}[1] Userspace${N} (recommended)"
  echo -e "      • No kernel module required — works on any VPS"
  echo -e "      • No reboot needed, even on Ubuntu 22.04"
  echo -e "      • Stable — no deadlocks"
  echo -e "      • Performance: ~70% of kernel (sufficient for VPN routing)"
  echo ""
  echo -e "  ${Y}[2] Kernel module${N}"
  echo -e "      • Maximum performance"
  echo -e "      • Requires PPA install + reboot on Ubuntu 22.04"
  echo -e "      • Known deadlock issues in AWG kernel module"
  echo ""
  if [[ $YES -eq 1 ]]; then
    AWG_MODE_CHOICE="1"
  else
    read -rp "  Choice [1]: " AWG_MODE_CHOICE
    AWG_MODE_CHOICE="${AWG_MODE_CHOICE:-1}"
  fi

  if [[ "$AWG_MODE_CHOICE" == "2" ]]; then
    AWG_USERSPACE_IMPL="kernel"
    ok "Run mode: Kernel module"
    apply_kernel_mode
  else
    AWG_USERSPACE_IMPL="amneziawg-go"
    ok "Run mode: Userspace (amneziawg-go)"
    apply_userspace_mode
  fi
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 2b — Network mode
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 2b: Network mode${N}"

if [[ "${NETWORK_MODE:-unset}" != "unset" && -n "${NETWORK_MODE:-}" ]]; then
  ok "Network mode: $NETWORK_MODE (loaded from .env)"
  if [[ $YES -eq 0 ]]; then
    read -rp "  Change network mode? [y/N]: " CHANGE_NET
    CHANGE_NET="${CHANGE_NET:-n}"
    [[ "${CHANGE_NET,,}" == "y" ]] && NETWORK_MODE=""
  fi
fi

if [[ -z "${NETWORK_MODE:-}" ]]; then
  echo ""
  echo -e "  ${B}Choose Docker network mode:${N}"
  echo -e "  ${G}[1] Host${N} (recommended)"
  echo -e "      • Container shares host network namespace"
  echo -e "      • No port range needed — all ports accessible directly"
  echo -e "      • Simplest setup, suitable for VPS"
  echo ""
  echo -e "  ${Y}[2] Bridge${N}"
  echo -e "      • Container has its own network namespace"
  echo -e "      • WireGuard UDP port range published by Docker (set at deploy time)"
  echo -e "      • Suitable when host networking is restricted or shared"
  echo ""
  if [[ $YES -eq 1 ]]; then
    NET_CHOICE="1"
  else
    read -rp "  Choice [1]: " NET_CHOICE
    NET_CHOICE="${NET_CHOICE:-1}"
  fi
  [[ "$NET_CHOICE" == "2" ]] && NETWORK_MODE="bridge" || NETWORK_MODE="host"
fi

ok "Network mode: $NETWORK_MODE"

# Bridge mode — collect and validate UDP port range
if [[ "$NETWORK_MODE" == "bridge" ]]; then
  if [[ -z "${BRIDGE_PORT_RANGE:-}" ]]; then
    if [[ $YES -eq 1 ]]; then
      BRIDGE_PORT_RANGE="51820-51899"
    else
      echo ""
      echo -e "  ${B}WireGuard UDP port range${N}"
      echo -e "  All WireGuard interfaces must use ports within this range."
      echo -e "  Expanding it later requires container restart."
      read -rp "  Port range [51820-51899]: " BRIDGE_PORT_RANGE
      BRIDGE_PORT_RANGE="${BRIDGE_PORT_RANGE:-51820-51899}"
    fi
  fi

  # Validate range — always, regardless of source (interactive, .env, or --yes default).
  # Prevents invalid values from reaching generate_bridge_compose sed substitution and SQLite.
  validate_port_range() {
    local range="$1"
    if [[ ! "$range" =~ ^([0-9]+)-([0-9]+)$ ]]; then
      fail "Invalid port range: '$range' — must be START-END (e.g. 51820-51899)"
    fi
    local start="${BASH_REMATCH[1]}" end="${BASH_REMATCH[2]}"
    [[ $start -ge $end ]] && fail "Port range start ($start) must be less than end ($end)"
    [[ $end -gt 65535 ]] && fail "Port $end exceeds maximum (65535)"
    [[ $start -lt 1024 ]] && warn "Port $start < 1024 — may require elevated privileges on some systems"
    _PORT_START="$start"
    _PORT_END="$end"
  }
  validate_port_range "$BRIDGE_PORT_RANGE"

  ok "WireGuard port range: $BRIDGE_PORT_RANGE ($_PORT_START–$_PORT_END, $(( _PORT_END - _PORT_START + 1 )) ports)"

  # In bridge mode Cascade must bind on all interfaces inside the container.
  # Docker's "127.0.0.1:PORT:PORT" publish restricts access to localhost on the host.
  BIND_ADDR="0.0.0.0"
else
  # Host mode (or explicit re-run switching back from bridge): ensure management port
  # is bound only to loopback. Without this reset, a previous bridge-mode BIND_ADDR=0.0.0.0
  # would persist in .env and expose the UI directly to the internet after the mode switch.
  BIND_ADDR="127.0.0.1"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 3 — Docker
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 3: Docker${N}"

if ! cascade_docker_install_required; then
  DOCKER_VER=$(docker --version | awk '{print $3}' | tr -d ,)
  ok "Docker ${DOCKER_VER} already installed"
else
  if command -v docker &>/dev/null; then
    warn "Detected distro-bundled docker.io — replacing with official Docker CE..."
  else
    info "Installing Docker (official)..."
  fi
  cascade_install_docker_ce "$OS_ID" "$OS_CODENAME" "$OS_VER"
  ok "Docker installed: $(docker --version | awk '{print $3}' | tr -d ,)"
fi

resolve_compose


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 4 — sysctl
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 4: Kernel parameters${N}"

SYSCTL_FILE="/etc/sysctl.d/99-cascade.conf"
if [[ -f "$SYSCTL_FILE" ]]; then
  ok "sysctl config already present"
else
  cat > "$SYSCTL_FILE" << 'SYSCTL'
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
net.core.rmem_max = 7340032
net.core.wmem_max = 7340032
SYSCTL
  sysctl --system -q
  ok "sysctl applied (ip_forward, UDP buffers)"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 4b — TCP/network stack tuning
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 4b: TCP/network tuning${N}"

TCP_TUNE_SCRIPT="$SCRIPT_DIR/tcp_tune.sh"
if [[ -f "$TCP_TUNE_SCRIPT" ]]; then
  if bash "$TCP_TUNE_SCRIPT"; then
    ok "TCP tuning applied (BBR, FQ, buffers, VPN-safe rp_filter)"
  else
    warn "TCP tuning script exited with errors (non-fatal)"
  fi
else
  warn "deploy/tcp_tune.sh not found — skipping TCP tuning"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 5a — Generate decoy video (QUIC streaming bait)
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 5a: Decoy video${N}"

VIDEO_DIR="$CADDY_DIR/www/video"
VIDEO_FILE="$VIDEO_DIR/decoy.mp4"
mkdir -p "$VIDEO_DIR"

if [[ -f "$VIDEO_FILE" ]]; then
  ok "decoy.mp4 already exists ($(du -sh "$VIDEO_FILE" | cut -f1))"
else
  if ! command -v ffmpeg &>/dev/null; then
    info "Installing ffmpeg..."
    apt-get install -y ffmpeg -qq
    ok "ffmpeg installed"
  fi

  # 480p noise video: easier to encode than 720p, still convincing as streaming.
  # noise=c0s=18 = TV-static intensity. ultrafast preset = CPU-friendly.
  # b:v 2000k → ~15 MB for 60s → browser re-fetches every loop = ~2 Mbps QUIC stream.
  # faststart = moov atom at front → playback starts before full download.
  info "Generating decoy.mp4 (480p noise, 60s — may take 1-2 min on slow CPUs)..."
  ffmpeg -y \
    -f lavfi -i "color=c=0x0f0f13:s=854x480:r=24" \
    -vf "noise=c0s=18:c0f=t,hue=s=0.1" \
    -t 60 \
    -c:v libx264 -b:v 2000k -preset ultrafast \
    -an \
    -movflags +faststart \
    "$VIDEO_FILE" > /tmp/cascade-ffmpeg.log 2>&1 &
  FFMPEG_PID=$!
  # Spinner so terminal doesn't look frozen
  SPIN='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'; si=0
  while kill -0 "$FFMPEG_PID" 2>/dev/null; do
    si=$(( (si+1) % 10 ))
    printf '\r    %s encoding...' "${SPIN:$si:1}"
    sleep 0.3
  done
  printf "\r"
  if wait "$FFMPEG_PID"; then
    ok "decoy.mp4 generated ($(du -sh "$VIDEO_FILE" | cut -f1), 60s, ~2 Mbps)"
  else
    warn "ffmpeg failed — decoy video skipped (log: /tmp/cascade-ffmpeg.log)"
    warn "Canvas noise fallback will be used instead"
  fi
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 5 — Pull Cascade image
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 5: Cascade image${N}"

cd "$RUNTIME_DIR"

info "Pulling the Cascade image configured in docker-compose.yml..."
compose_files "$RUNTIME_DIR/docker-compose.yml"
if $COMPOSE_CMD "${COMPOSE_ARGS[@]}" pull cascade; then
  ok "Cascade image pulled"
else
  fail "Could not pull the Cascade image configured in docker-compose.yml"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 6 — Collect configuration
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 6: Configuration${N}"

# WG_HOST
if [[ -z "${WG_HOST:-}" ]]; then
  DETECTED_IP=$(detect_ip)
  if [[ $YES -eq 1 ]]; then
    WG_HOST="${DETECTED_IP}"
  else
    read -rp "  Server public IP or domain [${DETECTED_IP}]: " WG_HOST_INPUT
    WG_HOST="${WG_HOST_INPUT:-$DETECTED_IP}"
  fi
fi
ok "WG_HOST = $WG_HOST"

# ADMIN_PATH
if [[ -z "${ADMIN_PATH:-}" ]]; then
  ADMIN_PATH=$(openssl rand -hex 16)
  info "Generated ADMIN_PATH: $ADMIN_PATH"
fi
ok "ADMIN_PATH = $ADMIN_PATH"

# ACME_EMAIL (optional)
if [[ -z "${ACME_EMAIL:-}" && $YES -eq 0 ]]; then
  read -rp "  Email for TLS certificate (optional, press Enter to skip): " ACME_EMAIL
fi

# Ports
CASCADE_PORT="${CASCADE_PORT:-8888}"
BIND_ADDR="${BIND_ADDR:-127.0.0.1}"

# Save all non-secret values
save_env
ok "Config saved to $ENV_FILE"

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 7 — Start Cascade
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 7: Cascade${N}"

# Select compose file based on network mode.
# Bridge: generate docker-compose.bridge.yml from template, then start it.
# Host:   use docker-compose.yml as-is (all config comes from .env).
if [[ "${NETWORK_MODE:-host}" == "bridge" ]]; then
  generate_bridge_compose "$BRIDGE_PORT_RANGE" "${CASCADE_PORT:-8888}"
  COMPOSE_FILE="$RUNTIME_DIR/docker-compose.bridge.yml"
else
  COMPOSE_FILE="$RUNTIME_DIR/docker-compose.yml"
fi

info "Starting Cascade ($NETWORK_MODE mode)..."
compose_files "$COMPOSE_FILE"
$COMPOSE_CMD "${COMPOSE_ARGS[@]}" down 2>/dev/null || true
$COMPOSE_CMD "${COMPOSE_ARGS[@]}" up -d

# Wait for health
info "Waiting for health check..."
for i in $(seq 1 90); do
  STATUS=$(curl -s --max-time 2 "http://127.0.0.1:${CASCADE_PORT}/api/health" 2>/dev/null | grep -o '"ok"' || true)
  if [[ "$STATUS" == '"ok"' ]]; then
    ok "Cascade healthy on 127.0.0.1:${CASCADE_PORT}"
    break
  fi
  sleep 1
  [[ $i -eq 90 ]] && fail "Cascade did not become healthy after 90s — check: docker logs cascade"
done

# Bridge mode: write PortPool to SQLite so Cascade auto-assigns only ports
# within the published range. Done after health check (DB is ready by then).
# Direct SQLite write is used because the REST API requires auth and no user
# exists yet at this point in setup.
if [[ "${NETWORK_MODE:-host}" == "bridge" ]]; then
  info "Setting PortPool = $BRIDGE_PORT_RANGE in Cascade settings..."
  if docker exec cascade sqlite3 /etc/wireguard/data/wireguard.db \
    "INSERT OR REPLACE INTO settings(key, value) VALUES('portPool', '${BRIDGE_PORT_RANGE}');"; then
    ok "PortPool set to $BRIDGE_PORT_RANGE"
  else
    warn "Could not set PortPool automatically — set it manually: Settings → Global → Port Pool"
  fi
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 8 — TLS certificate
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 8: TLS certificate (acme.sh)${N}"

# Select ACME server: staging or production
# Staging issues untrusted certificates — useful for testing without hitting rate limits.
# See: https://letsencrypt.org/docs/staging-environment/
if [[ "${ACME_STAGING:-0}" == "1" ]]; then
  ACME_SERVER="letsencrypt_test"
  warn "STAGING MODE: certificate will be issued by Let's Encrypt STAGING CA"
  warn "  → Browser will show 'Not secure' — this is expected for testing"
  warn "  → To switch to production: set ACME_STAGING=0 in .env and re-run"
else
  ACME_SERVER="letsencrypt"
fi

mkdir -p "$CERT_DIR"

# Ensure cron daemon is installed — required for automatic cert renewal.
# Minimal images may ship without cron; acme.sh --install-cronjob
# adds a crontab entry but the daemon must be running for it to fire.
if ! command -v crontab &>/dev/null; then
  info "Installing cron..."
  apt-get install -y -qq cron
  systemctl enable cron --now 2>/dev/null || true
  ok "cron installed and started"
else
  ok "cron already available"
fi

# Install the pinned and checksum-verified acme.sh release if needed.
if cascade_acme_install_required "$HOME/.acme.sh/acme.sh"; then
  info "Installing acme.sh..."
  cascade_install_acme_sh "${ACME_EMAIL:-}"
  # Verify the binary was actually created — fail loudly if installation silently failed.
  if [[ ! -f "$HOME/.acme.sh/acme.sh" ]]; then
    fail "acme.sh installation failed — binary not found at ~/.acme.sh/acme.sh"
  fi
  ok "acme.sh installed"
else
  ok "acme.sh already installed"
fi

ACME="$HOME/.acme.sh/acme.sh"

# Set RENEW_DAYS=1 — shortlived certs live 6 days (production) or 30 days (staging).
# Default RENEW_DAYS=30 → renewal fires every cron run for 6-day certs.
# With RENEW_DAYS=1 → renewal happens 1 day before expiry — correct for both modes.
if grep -q "^RENEW_DAYS=" "$HOME/.acme.sh/account.conf" 2>/dev/null; then
  sed -i 's/^RENEW_DAYS=.*/RENEW_DAYS=1/' "$HOME/.acme.sh/account.conf"
else
  echo 'RENEW_DAYS=1' >> "$HOME/.acme.sh/account.conf"
fi
ok "RENEW_DAYS=1 set in acme.sh account.conf"

# Install acme.sh cron job — required for automatic renewal.
# Without this the crontab entry is never created and 6-day shortlived certs expire.
# --install-cronjob is idempotent: safe to call on every setup run.
"$ACME" --install-cronjob
ok "acme.sh cron job installed (automatic renewal enabled)"

# Check if cert already exists and is valid
if [[ -f "$CERT_DIR/server.crt" ]]; then
  EXPIRY=$(openssl x509 -in "$CERT_DIR/server.crt" -noout -enddate 2>/dev/null | cut -d= -f2 || true)
  # Detect if existing cert is staging vs production
  ISSUER=$(openssl x509 -in "$CERT_DIR/server.crt" -noout -issuer 2>/dev/null || true)
  if echo "$ISSUER" | grep -qi "staging\|fake\|bogus"; then
    CERT_MODE="staging"
  elif echo "$ISSUER" | grep -qi "^issuer= */CN=$WG_HOST\|self.signed\|self-signed"; then
    CERT_MODE="self-signed"
  elif openssl verify -CAfile "$CERT_DIR/server.crt" "$CERT_DIR/server.crt" &>/dev/null; then
    CERT_MODE="self-signed"
  else
    CERT_MODE="production"
  fi
  ok "Certificate already present (expires: $EXPIRY, mode: $CERT_MODE)"
  ATTEMPT_LE=0
  if [[ "$CERT_MODE" == "self-signed" ]]; then
    warn "Existing cert is SELF-SIGNED — will attempt Let's Encrypt upgrade"
    warn "If LE succeeds, self-signed will be replaced. If not, self-signed is kept."
    ATTEMPT_LE=1
  elif [[ "$CERT_MODE" == "staging" && "${ACME_STAGING:-0}" != "1" ]]; then
    warn "Existing cert is STAGING but ACME_STAGING=0 — deleting and reissuing production cert"
    rm -f "$CERT_DIR/server.crt" "$CERT_DIR/server.key"
    "$ACME" --remove -d "$WG_HOST" 2>/dev/null || true
  elif [[ "$CERT_MODE" == "production" && "${ACME_STAGING:-0}" == "1" ]]; then
    warn "Existing cert is PRODUCTION but --staging requested — keeping production cert"
    info "To force staging reissue: rm -f $CERT_DIR/server.crt $CERT_DIR/server.key && re-run setup"
  else
    info "Skipping issuance — to reissue: $ACME --issue --force --server $ACME_SERVER -d $WG_HOST ..."
  fi
fi

if [[ ! -f "$CERT_DIR/server.crt" || "${ATTEMPT_LE:-0}" == "1" ]]; then
  info "Issuing TLS certificate for: $WG_HOST (server: $ACME_SERVER)"

  # --cert-profile shortlived required for bare IP identifiers.
  # Without it LE rejects with "Default profile does not permit IP address identifiers."
  SHORTLIVED_ARGS=()
  is_ip "$WG_HOST" && SHORTLIVED_ARGS=(--cert-profile shortlived)

  # Try Let's Encrypt via standalone (Caddy not yet running — chicken-and-egg).
  # Port 80 fallback: if already occupied, try webroot directly.
  # If LE fails for any reason (port 80 blocked, private IP, rate limit, no public IP)
  # fall back to self-signed — Caddy starts, cert can be replaced later with real one.
  LE_SUCCESS=0
  if ss -tlnp 2>/dev/null | grep -q ':80 '; then
    warn "Port 80 is already in use — attempting webroot mode via /srv/acme"
    mkdir -p /srv/acme
    "$ACME" --issue --server "$ACME_SERVER" \
      -d "$WG_HOST" --webroot /srv/acme \
      "${SHORTLIVED_ARGS[@]}" && LE_SUCCESS=1 || true
  else
    "$ACME" --issue --server "$ACME_SERVER" \
      -d "$WG_HOST" --standalone \
      "${SHORTLIVED_ARGS[@]}" && LE_SUCCESS=1 || true
  fi

  if [[ $LE_SUCCESS -eq 1 ]]; then
    # Install cert.
    # reloadcmd = docker restart (NOT caddy reload — admin off disables the admin API).
    # "No such container" on first run is expected — Caddy starts in Step 9.
    "$ACME" --install-cert -d "$WG_HOST" --ecc \
      --key-file       "$CERT_DIR/server.key" \
      --fullchain-file "$CERT_DIR/server.crt" \
      --reloadcmd      "docker restart cascade-caddy 2>/dev/null || true" || true
    ok "Let's Encrypt certificate installed to $CERT_DIR"
  else
    # Fallback: self-signed certificate.
    # Happens when: port 80 blocked, private/unknown IP, LE rate limit, no internet.
    # Caddy will show browser warning — replace cert later by re-running setup.sh
    # or by placing real cert files in $CERT_DIR and running: docker restart cascade-caddy
    warn "Let's Encrypt failed — generating self-signed certificate (valid 10 years)"
    warn "Browser will show 'Not secure'. To replace: re-run setup.sh when port 80 is open,"
    warn "or place your own cert in $CERT_DIR/{server.crt,server.key} + docker restart cascade-caddy"
    openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:P-256 \
      -keyout "$CERT_DIR/server.key" \
      -out    "$CERT_DIR/server.crt" \
      -days   3650 -nodes \
      -subj   "/CN=$WG_HOST" \
      -addext "subjectAltName=IP:$WG_HOST" 2>/dev/null \
      || openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:P-256 \
           -keyout "$CERT_DIR/server.key" \
           -out    "$CERT_DIR/server.crt" \
           -days   3650 -nodes \
           -subj   "/CN=$WG_HOST" 2>/dev/null
    ok "Self-signed certificate generated (10 years)"
  fi

  chmod 600 "$CERT_DIR/server.key"
  chmod 644 "$CERT_DIR/server.crt"
  ok "Certificate installed to $CERT_DIR"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 9 — Caddy reverse proxy
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 9: Caddy reverse proxy${N}"

info "Starting Caddy..."
cd "$CADDY_DIR"
$COMPOSE_CMD down 2>/dev/null || true
$COMPOSE_CMD up -d

# Wait for Caddy
sleep 2
if docker ps --filter "name=cascade-caddy" --filter "status=running" | grep -q cascade-caddy; then
  ok "Caddy running"
else
  fail "Caddy failed to start — check: $COMPOSE_CMD -f deploy/caddy/docker-compose.yml logs"
fi

# Switch acme.sh to webroot mode now that Caddy is running.
# After standalone issuance Le_Webroot='no' is saved in acme.sh config.
# If left as-is, future cron renewals try standalone again → port 80 conflict with Caddy → fail.
#
# IMPORTANT: do NOT use --issue --force here — it re-issues a new certificate which:
#   1. Consumes LE rate limit (5 certs per 7 days per IP)
#   2. Overwrites Le_CertCreateTime → Le_NextRenewTime is recalculated from new issue time,
#      not from the actual cert expiry → cron fires too late → cert expires before renewal
#
# Instead: patch Le_Webroot directly in the acme.sh domain config file.
# acme.sh reads Le_Webroot on every renewal run — patching it is safe and official practice.
ACME_DOMAIN_CONF="$HOME/.acme.sh/${WG_HOST}_ecc/${WG_HOST}.conf"
if [[ -f "$ACME_DOMAIN_CONF" ]]; then
  CURRENT_WEBROOT=$(grep "^Le_Webroot=" "$ACME_DOMAIN_CONF" 2>/dev/null | cut -d= -f2 | tr -d "'" || true)
  if [[ "$CURRENT_WEBROOT" != "/srv/acme" ]]; then
    info "Switching acme.sh to webroot mode (patching config, no new cert issued)..."
    mkdir -p /srv/acme
    sed -i "s|^Le_Webroot=.*|Le_Webroot='/srv/acme'|" "$ACME_DOMAIN_CONF"
    ok "Webroot mode set — renewals will use /srv/acme via Caddy"
  else
    ok "acme.sh already in webroot mode"
  fi

  # Also fix Le_NextRenewTime based on actual cert expiry (not last --issue time).
  # Compute: cert_expiry_unix - RENEW_DAYS(1) * 86400
  CERT_EXPIRY_UNIX=$(openssl x509 -in "$CERT_DIR/server.crt" -noout -enddate 2>/dev/null \
    | cut -d= -f2 | xargs -I{} date -d "{}" +%s 2>/dev/null || echo "")
  if [[ -n "$CERT_EXPIRY_UNIX" ]]; then
    RENEW_AT=$(( CERT_EXPIRY_UNIX - 86400 ))
    RENEW_AT_STR=$(date -u -d "@$RENEW_AT" +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || true)
    if [[ -n "$RENEW_AT_STR" ]]; then
      sed -i "s|^Le_NextRenewTime=.*|Le_NextRenewTime='$RENEW_AT'|" "$ACME_DOMAIN_CONF"
      sed -i "s|^Le_NextRenewTimeStr=.*|Le_NextRenewTimeStr='$RENEW_AT_STR'|" "$ACME_DOMAIN_CONF"
      ok "NextRenewTime set to $RENEW_AT_STR (1 day before cert expiry)"
    fi
  fi
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 10 — Verify
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 10: Verification${N}"

cd "$RUNTIME_DIR"

DECOY=$(curl -sk --max-time 5 "https://${WG_HOST}/" 2>/dev/null | grep -o 'StreamVault' || true)
if [[ "$DECOY" == "StreamVault" ]]; then
  ok "Decoy site reachable (StreamVault)"
else
  warn "Decoy site check failed — may need a few seconds"
fi

ADMIN=$(curl -sk --max-time 5 "https://${WG_HOST}/${ADMIN_PATH}/api/health" 2>/dev/null | grep -o '"ok"' || true)
if [[ "$ADMIN" == '"ok"' ]]; then
  ok "Admin API reachable via Caddy"
else
  warn "Admin API check failed — check Caddy logs"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# Summary
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${G}╔══════════════════════════════════════════════════════╗${N}"
echo -e "${G}║               Cascade — Setup Complete               ║${N}"
echo -e "${G}╚══════════════════════════════════════════════════════╝${N}"
echo ""
echo -e "  Admin URL:   ${G}https://${WG_HOST}/${ADMIN_PATH}/${N}"
echo -e "  Network mode: ${B}${NETWORK_MODE:-host}${N}"
[[ "${NETWORK_MODE:-host}" == "bridge" ]] && \
  echo -e "  WG UDP range: ${B}${BRIDGE_PORT_RANGE}${N} (published by Docker)"
echo ""
echo -e "  ${Y}First login:${N}"
echo -e "    1. Open the URL above in your browser"
echo -e "    2. You will see a ${B}Create First User${N} form (open mode)"
echo -e "    3. Create your admin account"
echo -e "    4. Enable TOTP in Settings → Users for added security"
echo ""
echo -e "  ${Y}Update:${N}"
echo -e "    Edit the image tag in $RUNTIME_DIR/docker-compose.yml"
echo -e "    cd $RUNTIME_DIR && sudo docker compose pull && sudo docker compose up -d"
echo ""
echo -e "  ${Y}Logs:${N}"
echo -e "    docker logs cascade"
echo -e "    docker compose -f deploy/caddy/docker-compose.yml logs"
echo ""
echo -e "  Runtime dir:  ${B}${RUNTIME_DIR}${N}"
echo -e "  Config saved: ${B}${ENV_FILE}${N}"
echo ""
